;; tabletop-access-ycb — dense YCB tabletop-access (fork of access).
;; Per-footprint-size pick_<W>x<H> / put_<W>x<H> schemas; W·H cell
;; params pinned into a rigid block by (adjacent …) statics so every
;; covered cell's occupancy updates.  Pure STRIPS+typing.
;; Footprint sizes present: 2x2, 2x3, 2x4, 3x3, 3x4, 4x4

(define (domain tabletop-access-ycb)
  (:requirements :strips :typing)

  (:types cell movable direction)

  (:constants north east - direction)

  (:predicates
    (adjacent ?dir - direction ?cel1 - cell ?cel2 - cell)
    (occupied ?cel - cell ?obj - movable)
    (empty ?cel - cell)
    (holding ?obj - movable)
    (gripper-empty)
    (fp_2x2 ?o - movable)
    (fp_2x3 ?o - movable)
    (fp_2x4 ?o - movable)
    (fp_3x3 ?o - movable)
    (fp_3x4 ?o - movable)
    (fp_4x4 ?o - movable)
  )

  (:action pick_2x2
    :parameters (?o - movable ?c0_0 ?c0_1 ?c1_0 ?c1_1 - cell)
    :precondition (and
      (gripper-empty)
      (fp_2x2 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c1_0 ?c1_1)
      (occupied ?c0_0 ?o)
      (occupied ?c0_1 ?o)
      (occupied ?c1_0 ?o)
      (occupied ?c1_1 ?o)
    )
    :effect (and
      (not (gripper-empty))
      (holding ?o)
      (not (occupied ?c0_0 ?o))
      (empty ?c0_0)
      (not (occupied ?c0_1 ?o))
      (empty ?c0_1)
      (not (occupied ?c1_0 ?o))
      (empty ?c1_0)
      (not (occupied ?c1_1 ?o))
      (empty ?c1_1)
    )
  )

  (:action put_2x2
    :parameters (?o - movable ?c0_0 ?c0_1 ?c1_0 ?c1_1 - cell)
    :precondition (and
      (holding ?o)
      (fp_2x2 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c1_0 ?c1_1)
      (empty ?c0_0)
      (empty ?c0_1)
      (empty ?c1_0)
      (empty ?c1_1)
    )
    :effect (and
      (gripper-empty)
      (not (holding ?o))
      (occupied ?c0_0 ?o)
      (not (empty ?c0_0))
      (occupied ?c0_1 ?o)
      (not (empty ?c0_1))
      (occupied ?c1_0 ?o)
      (not (empty ?c1_0))
      (occupied ?c1_1 ?o)
      (not (empty ?c1_1))
    )
  )

  (:action pick_2x3
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c1_0 ?c1_1 ?c1_2 - cell)
    :precondition (and
      (gripper-empty)
      (fp_2x3 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent north ?c1_1 ?c1_2)
      (occupied ?c0_0 ?o)
      (occupied ?c0_1 ?o)
      (occupied ?c0_2 ?o)
      (occupied ?c1_0 ?o)
      (occupied ?c1_1 ?o)
      (occupied ?c1_2 ?o)
    )
    :effect (and
      (not (gripper-empty))
      (holding ?o)
      (not (occupied ?c0_0 ?o))
      (empty ?c0_0)
      (not (occupied ?c0_1 ?o))
      (empty ?c0_1)
      (not (occupied ?c0_2 ?o))
      (empty ?c0_2)
      (not (occupied ?c1_0 ?o))
      (empty ?c1_0)
      (not (occupied ?c1_1 ?o))
      (empty ?c1_1)
      (not (occupied ?c1_2 ?o))
      (empty ?c1_2)
    )
  )

  (:action put_2x3
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c1_0 ?c1_1 ?c1_2 - cell)
    :precondition (and
      (holding ?o)
      (fp_2x3 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent north ?c1_1 ?c1_2)
      (empty ?c0_0)
      (empty ?c0_1)
      (empty ?c0_2)
      (empty ?c1_0)
      (empty ?c1_1)
      (empty ?c1_2)
    )
    :effect (and
      (gripper-empty)
      (not (holding ?o))
      (occupied ?c0_0 ?o)
      (not (empty ?c0_0))
      (occupied ?c0_1 ?o)
      (not (empty ?c0_1))
      (occupied ?c0_2 ?o)
      (not (empty ?c0_2))
      (occupied ?c1_0 ?o)
      (not (empty ?c1_0))
      (occupied ?c1_1 ?o)
      (not (empty ?c1_1))
      (occupied ?c1_2 ?o)
      (not (empty ?c1_2))
    )
  )

  (:action pick_2x4
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c0_3 ?c1_0 ?c1_1 ?c1_2 ?c1_3 - cell)
    :precondition (and
      (gripper-empty)
      (fp_2x4 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent north ?c0_2 ?c0_3)
      (adjacent east ?c0_3 ?c1_3)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent north ?c1_1 ?c1_2)
      (adjacent north ?c1_2 ?c1_3)
      (occupied ?c0_0 ?o)
      (occupied ?c0_1 ?o)
      (occupied ?c0_2 ?o)
      (occupied ?c0_3 ?o)
      (occupied ?c1_0 ?o)
      (occupied ?c1_1 ?o)
      (occupied ?c1_2 ?o)
      (occupied ?c1_3 ?o)
    )
    :effect (and
      (not (gripper-empty))
      (holding ?o)
      (not (occupied ?c0_0 ?o))
      (empty ?c0_0)
      (not (occupied ?c0_1 ?o))
      (empty ?c0_1)
      (not (occupied ?c0_2 ?o))
      (empty ?c0_2)
      (not (occupied ?c0_3 ?o))
      (empty ?c0_3)
      (not (occupied ?c1_0 ?o))
      (empty ?c1_0)
      (not (occupied ?c1_1 ?o))
      (empty ?c1_1)
      (not (occupied ?c1_2 ?o))
      (empty ?c1_2)
      (not (occupied ?c1_3 ?o))
      (empty ?c1_3)
    )
  )

  (:action put_2x4
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c0_3 ?c1_0 ?c1_1 ?c1_2 ?c1_3 - cell)
    :precondition (and
      (holding ?o)
      (fp_2x4 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent north ?c0_2 ?c0_3)
      (adjacent east ?c0_3 ?c1_3)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent north ?c1_1 ?c1_2)
      (adjacent north ?c1_2 ?c1_3)
      (empty ?c0_0)
      (empty ?c0_1)
      (empty ?c0_2)
      (empty ?c0_3)
      (empty ?c1_0)
      (empty ?c1_1)
      (empty ?c1_2)
      (empty ?c1_3)
    )
    :effect (and
      (gripper-empty)
      (not (holding ?o))
      (occupied ?c0_0 ?o)
      (not (empty ?c0_0))
      (occupied ?c0_1 ?o)
      (not (empty ?c0_1))
      (occupied ?c0_2 ?o)
      (not (empty ?c0_2))
      (occupied ?c0_3 ?o)
      (not (empty ?c0_3))
      (occupied ?c1_0 ?o)
      (not (empty ?c1_0))
      (occupied ?c1_1 ?o)
      (not (empty ?c1_1))
      (occupied ?c1_2 ?o)
      (not (empty ?c1_2))
      (occupied ?c1_3 ?o)
      (not (empty ?c1_3))
    )
  )

  (:action pick_3x3
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c1_0 ?c1_1 ?c1_2 ?c2_0 ?c2_1 ?c2_2 - cell)
    :precondition (and
      (gripper-empty)
      (fp_3x3 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent east ?c1_0 ?c2_0)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent east ?c1_1 ?c2_1)
      (adjacent north ?c1_1 ?c1_2)
      (adjacent east ?c1_2 ?c2_2)
      (adjacent north ?c2_0 ?c2_1)
      (adjacent north ?c2_1 ?c2_2)
      (occupied ?c0_0 ?o)
      (occupied ?c0_1 ?o)
      (occupied ?c0_2 ?o)
      (occupied ?c1_0 ?o)
      (occupied ?c1_1 ?o)
      (occupied ?c1_2 ?o)
      (occupied ?c2_0 ?o)
      (occupied ?c2_1 ?o)
      (occupied ?c2_2 ?o)
    )
    :effect (and
      (not (gripper-empty))
      (holding ?o)
      (not (occupied ?c0_0 ?o))
      (empty ?c0_0)
      (not (occupied ?c0_1 ?o))
      (empty ?c0_1)
      (not (occupied ?c0_2 ?o))
      (empty ?c0_2)
      (not (occupied ?c1_0 ?o))
      (empty ?c1_0)
      (not (occupied ?c1_1 ?o))
      (empty ?c1_1)
      (not (occupied ?c1_2 ?o))
      (empty ?c1_2)
      (not (occupied ?c2_0 ?o))
      (empty ?c2_0)
      (not (occupied ?c2_1 ?o))
      (empty ?c2_1)
      (not (occupied ?c2_2 ?o))
      (empty ?c2_2)
    )
  )

  (:action put_3x3
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c1_0 ?c1_1 ?c1_2 ?c2_0 ?c2_1 ?c2_2 - cell)
    :precondition (and
      (holding ?o)
      (fp_3x3 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent east ?c1_0 ?c2_0)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent east ?c1_1 ?c2_1)
      (adjacent north ?c1_1 ?c1_2)
      (adjacent east ?c1_2 ?c2_2)
      (adjacent north ?c2_0 ?c2_1)
      (adjacent north ?c2_1 ?c2_2)
      (empty ?c0_0)
      (empty ?c0_1)
      (empty ?c0_2)
      (empty ?c1_0)
      (empty ?c1_1)
      (empty ?c1_2)
      (empty ?c2_0)
      (empty ?c2_1)
      (empty ?c2_2)
    )
    :effect (and
      (gripper-empty)
      (not (holding ?o))
      (occupied ?c0_0 ?o)
      (not (empty ?c0_0))
      (occupied ?c0_1 ?o)
      (not (empty ?c0_1))
      (occupied ?c0_2 ?o)
      (not (empty ?c0_2))
      (occupied ?c1_0 ?o)
      (not (empty ?c1_0))
      (occupied ?c1_1 ?o)
      (not (empty ?c1_1))
      (occupied ?c1_2 ?o)
      (not (empty ?c1_2))
      (occupied ?c2_0 ?o)
      (not (empty ?c2_0))
      (occupied ?c2_1 ?o)
      (not (empty ?c2_1))
      (occupied ?c2_2 ?o)
      (not (empty ?c2_2))
    )
  )

  (:action pick_3x4
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c0_3 ?c1_0 ?c1_1 ?c1_2 ?c1_3 ?c2_0 ?c2_1 ?c2_2 ?c2_3 - cell)
    :precondition (and
      (gripper-empty)
      (fp_3x4 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent north ?c0_2 ?c0_3)
      (adjacent east ?c0_3 ?c1_3)
      (adjacent east ?c1_0 ?c2_0)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent east ?c1_1 ?c2_1)
      (adjacent north ?c1_1 ?c1_2)
      (adjacent east ?c1_2 ?c2_2)
      (adjacent north ?c1_2 ?c1_3)
      (adjacent east ?c1_3 ?c2_3)
      (adjacent north ?c2_0 ?c2_1)
      (adjacent north ?c2_1 ?c2_2)
      (adjacent north ?c2_2 ?c2_3)
      (occupied ?c0_0 ?o)
      (occupied ?c0_1 ?o)
      (occupied ?c0_2 ?o)
      (occupied ?c0_3 ?o)
      (occupied ?c1_0 ?o)
      (occupied ?c1_1 ?o)
      (occupied ?c1_2 ?o)
      (occupied ?c1_3 ?o)
      (occupied ?c2_0 ?o)
      (occupied ?c2_1 ?o)
      (occupied ?c2_2 ?o)
      (occupied ?c2_3 ?o)
    )
    :effect (and
      (not (gripper-empty))
      (holding ?o)
      (not (occupied ?c0_0 ?o))
      (empty ?c0_0)
      (not (occupied ?c0_1 ?o))
      (empty ?c0_1)
      (not (occupied ?c0_2 ?o))
      (empty ?c0_2)
      (not (occupied ?c0_3 ?o))
      (empty ?c0_3)
      (not (occupied ?c1_0 ?o))
      (empty ?c1_0)
      (not (occupied ?c1_1 ?o))
      (empty ?c1_1)
      (not (occupied ?c1_2 ?o))
      (empty ?c1_2)
      (not (occupied ?c1_3 ?o))
      (empty ?c1_3)
      (not (occupied ?c2_0 ?o))
      (empty ?c2_0)
      (not (occupied ?c2_1 ?o))
      (empty ?c2_1)
      (not (occupied ?c2_2 ?o))
      (empty ?c2_2)
      (not (occupied ?c2_3 ?o))
      (empty ?c2_3)
    )
  )

  (:action put_3x4
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c0_3 ?c1_0 ?c1_1 ?c1_2 ?c1_3 ?c2_0 ?c2_1 ?c2_2 ?c2_3 - cell)
    :precondition (and
      (holding ?o)
      (fp_3x4 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent north ?c0_2 ?c0_3)
      (adjacent east ?c0_3 ?c1_3)
      (adjacent east ?c1_0 ?c2_0)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent east ?c1_1 ?c2_1)
      (adjacent north ?c1_1 ?c1_2)
      (adjacent east ?c1_2 ?c2_2)
      (adjacent north ?c1_2 ?c1_3)
      (adjacent east ?c1_3 ?c2_3)
      (adjacent north ?c2_0 ?c2_1)
      (adjacent north ?c2_1 ?c2_2)
      (adjacent north ?c2_2 ?c2_3)
      (empty ?c0_0)
      (empty ?c0_1)
      (empty ?c0_2)
      (empty ?c0_3)
      (empty ?c1_0)
      (empty ?c1_1)
      (empty ?c1_2)
      (empty ?c1_3)
      (empty ?c2_0)
      (empty ?c2_1)
      (empty ?c2_2)
      (empty ?c2_3)
    )
    :effect (and
      (gripper-empty)
      (not (holding ?o))
      (occupied ?c0_0 ?o)
      (not (empty ?c0_0))
      (occupied ?c0_1 ?o)
      (not (empty ?c0_1))
      (occupied ?c0_2 ?o)
      (not (empty ?c0_2))
      (occupied ?c0_3 ?o)
      (not (empty ?c0_3))
      (occupied ?c1_0 ?o)
      (not (empty ?c1_0))
      (occupied ?c1_1 ?o)
      (not (empty ?c1_1))
      (occupied ?c1_2 ?o)
      (not (empty ?c1_2))
      (occupied ?c1_3 ?o)
      (not (empty ?c1_3))
      (occupied ?c2_0 ?o)
      (not (empty ?c2_0))
      (occupied ?c2_1 ?o)
      (not (empty ?c2_1))
      (occupied ?c2_2 ?o)
      (not (empty ?c2_2))
      (occupied ?c2_3 ?o)
      (not (empty ?c2_3))
    )
  )

  (:action pick_4x4
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c0_3 ?c1_0 ?c1_1 ?c1_2 ?c1_3 ?c2_0 ?c2_1 ?c2_2 ?c2_3 ?c3_0 ?c3_1 ?c3_2 ?c3_3 - cell)
    :precondition (and
      (gripper-empty)
      (fp_4x4 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent north ?c0_2 ?c0_3)
      (adjacent east ?c0_3 ?c1_3)
      (adjacent east ?c1_0 ?c2_0)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent east ?c1_1 ?c2_1)
      (adjacent north ?c1_1 ?c1_2)
      (adjacent east ?c1_2 ?c2_2)
      (adjacent north ?c1_2 ?c1_3)
      (adjacent east ?c1_3 ?c2_3)
      (adjacent east ?c2_0 ?c3_0)
      (adjacent north ?c2_0 ?c2_1)
      (adjacent east ?c2_1 ?c3_1)
      (adjacent north ?c2_1 ?c2_2)
      (adjacent east ?c2_2 ?c3_2)
      (adjacent north ?c2_2 ?c2_3)
      (adjacent east ?c2_3 ?c3_3)
      (adjacent north ?c3_0 ?c3_1)
      (adjacent north ?c3_1 ?c3_2)
      (adjacent north ?c3_2 ?c3_3)
      (occupied ?c0_0 ?o)
      (occupied ?c0_1 ?o)
      (occupied ?c0_2 ?o)
      (occupied ?c0_3 ?o)
      (occupied ?c1_0 ?o)
      (occupied ?c1_1 ?o)
      (occupied ?c1_2 ?o)
      (occupied ?c1_3 ?o)
      (occupied ?c2_0 ?o)
      (occupied ?c2_1 ?o)
      (occupied ?c2_2 ?o)
      (occupied ?c2_3 ?o)
      (occupied ?c3_0 ?o)
      (occupied ?c3_1 ?o)
      (occupied ?c3_2 ?o)
      (occupied ?c3_3 ?o)
    )
    :effect (and
      (not (gripper-empty))
      (holding ?o)
      (not (occupied ?c0_0 ?o))
      (empty ?c0_0)
      (not (occupied ?c0_1 ?o))
      (empty ?c0_1)
      (not (occupied ?c0_2 ?o))
      (empty ?c0_2)
      (not (occupied ?c0_3 ?o))
      (empty ?c0_3)
      (not (occupied ?c1_0 ?o))
      (empty ?c1_0)
      (not (occupied ?c1_1 ?o))
      (empty ?c1_1)
      (not (occupied ?c1_2 ?o))
      (empty ?c1_2)
      (not (occupied ?c1_3 ?o))
      (empty ?c1_3)
      (not (occupied ?c2_0 ?o))
      (empty ?c2_0)
      (not (occupied ?c2_1 ?o))
      (empty ?c2_1)
      (not (occupied ?c2_2 ?o))
      (empty ?c2_2)
      (not (occupied ?c2_3 ?o))
      (empty ?c2_3)
      (not (occupied ?c3_0 ?o))
      (empty ?c3_0)
      (not (occupied ?c3_1 ?o))
      (empty ?c3_1)
      (not (occupied ?c3_2 ?o))
      (empty ?c3_2)
      (not (occupied ?c3_3 ?o))
      (empty ?c3_3)
    )
  )

  (:action put_4x4
    :parameters (?o - movable ?c0_0 ?c0_1 ?c0_2 ?c0_3 ?c1_0 ?c1_1 ?c1_2 ?c1_3 ?c2_0 ?c2_1 ?c2_2 ?c2_3 ?c3_0 ?c3_1 ?c3_2 ?c3_3 - cell)
    :precondition (and
      (holding ?o)
      (fp_4x4 ?o)
      (adjacent east ?c0_0 ?c1_0)
      (adjacent north ?c0_0 ?c0_1)
      (adjacent east ?c0_1 ?c1_1)
      (adjacent north ?c0_1 ?c0_2)
      (adjacent east ?c0_2 ?c1_2)
      (adjacent north ?c0_2 ?c0_3)
      (adjacent east ?c0_3 ?c1_3)
      (adjacent east ?c1_0 ?c2_0)
      (adjacent north ?c1_0 ?c1_1)
      (adjacent east ?c1_1 ?c2_1)
      (adjacent north ?c1_1 ?c1_2)
      (adjacent east ?c1_2 ?c2_2)
      (adjacent north ?c1_2 ?c1_3)
      (adjacent east ?c1_3 ?c2_3)
      (adjacent east ?c2_0 ?c3_0)
      (adjacent north ?c2_0 ?c2_1)
      (adjacent east ?c2_1 ?c3_1)
      (adjacent north ?c2_1 ?c2_2)
      (adjacent east ?c2_2 ?c3_2)
      (adjacent north ?c2_2 ?c2_3)
      (adjacent east ?c2_3 ?c3_3)
      (adjacent north ?c3_0 ?c3_1)
      (adjacent north ?c3_1 ?c3_2)
      (adjacent north ?c3_2 ?c3_3)
      (empty ?c0_0)
      (empty ?c0_1)
      (empty ?c0_2)
      (empty ?c0_3)
      (empty ?c1_0)
      (empty ?c1_1)
      (empty ?c1_2)
      (empty ?c1_3)
      (empty ?c2_0)
      (empty ?c2_1)
      (empty ?c2_2)
      (empty ?c2_3)
      (empty ?c3_0)
      (empty ?c3_1)
      (empty ?c3_2)
      (empty ?c3_3)
    )
    :effect (and
      (gripper-empty)
      (not (holding ?o))
      (occupied ?c0_0 ?o)
      (not (empty ?c0_0))
      (occupied ?c0_1 ?o)
      (not (empty ?c0_1))
      (occupied ?c0_2 ?o)
      (not (empty ?c0_2))
      (occupied ?c0_3 ?o)
      (not (empty ?c0_3))
      (occupied ?c1_0 ?o)
      (not (empty ?c1_0))
      (occupied ?c1_1 ?o)
      (not (empty ?c1_1))
      (occupied ?c1_2 ?o)
      (not (empty ?c1_2))
      (occupied ?c1_3 ?o)
      (not (empty ?c1_3))
      (occupied ?c2_0 ?o)
      (not (empty ?c2_0))
      (occupied ?c2_1 ?o)
      (not (empty ?c2_1))
      (occupied ?c2_2 ?o)
      (not (empty ?c2_2))
      (occupied ?c2_3 ?o)
      (not (empty ?c2_3))
      (occupied ?c3_0 ?o)
      (not (empty ?c3_0))
      (occupied ?c3_1 ?o)
      (not (empty ?c3_1))
      (occupied ?c3_2 ?o)
      (not (empty ?c3_2))
      (occupied ?c3_3 ?o)
      (not (empty ?c3_3))
    )
  )
)
