"""access-19 dataset generation — PDDL problems with feasibility validation.

Mirrors :mod:`tampanda.symbolic.domains.multilevel_blocks.generate_data`:

1. A template is sampled (front_row_subset / dense_front /
   scattered_subset / gotcha_corridor_jam / canonical_18, with mirror
   ops applied to half the instances).
2. The initial layout + goal layout are derived from the template.
3. A plan is generated by the search planner — :func:`oracle_plan` for
   OoI-only goals, :func:`astar_plan` for return goals at L1-L3,
   :func:`phased_plan` for L4-scale return goals.
4. The full action sequence is replayed through
   :func:`check_action_sequence` (FAST mode) and rejected if any
   action fails.  This is the same FAST↔FULL agreement contract used
   by ``access19_feasibility_smoke.py``.
5. PDDL problem + plan + meta are written to disk.

Output layout::

    data/access19/
    ├── domain.pddl
    ├── train/
    │   ├── L0/config_1.pddl
    │   ├── L0/config_1.pddl.plan
    │   └── ...
    ├── test/
    └── val/

Usage::

    python -m tampanda.symbolic.domains.access19.generate_data \\
        --curriculum-spec train_120 --num-workers 4 \\
        --output-dir data/access19

    python -m tampanda.symbolic.domains.access19.generate_data \\
        --level 2 --num 30 --split val \\
        --output-dir data/access19
"""
from __future__ import annotations

import argparse
import multiprocessing as mp
import shutil
import tempfile
import time
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

from tampanda.symbolic.domains.access19 import (
    apply_runtime_tweaks, make_access19_builder,
    make_access19_pick_fn, make_access19_put_fn,
)
from tampanda.symbolic.domains.access19.feasibility import (
    check_action_sequence,
)
from tampanda.symbolic.domains.access19.parallel import _layout_to_state
from tampanda.symbolic.domains.access19.planner import (
    astar_plan, oracle_plan, phased_plan,
)
from tampanda.symbolic.domains.access19.reachability import (
    _build_executor, _solve_access19_staging,
)
from tampanda.symbolic.domains.access19.templates import (
    Template,
    canonical_18,
    dense_front,
    front_row_subset,
    goal_layout as template_goal_layout,
    gotcha_corridor_jam,
    mirror_x,
    scattered_subset,
    source_layout as template_source_layout,
)
from tampanda.symbolic.workspace import Cell
from tampanda.planners.grasp_planner import GraspType
from tampanda.planners.linear_ik import LinearIKPlanner


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_HERE = Path(__file__).parent
_DOMAIN = (_HERE / "pddl" / "domain.pddl").resolve()

_DEFAULT_OUTPUT_DIR = Path("data/access19")
_DEFAULT_TRAIN = 24
_DEFAULT_VAL = 6
_DEFAULT_TEST = 6
_DEFAULT_NUM_WORKERS = 1
_DEFAULT_SEED = 42

# Templates allowed per level.  L0/L1 = OoI-only goal; L2+ = return-all
# goal (specified via the ``return_blockers`` kwarg in the sampler).
_LEVEL_TEMPLATE_NAMES: Dict[int, List[str]] = {
    0: ["front_row_subset"],     # n=0..1, return=False
    1: ["front_row_subset"],     # n=2..3, return=False
    2: ["dense_front", "scattered_subset"],   # n_rows<=2 / n<=6, return=True
    3: ["dense_front", "scattered_subset", "gotcha_corridor_jam"],
    4: ["canonical_18"],         # 18 blockers, return=True (uses phased)
}

# Planner choice per level — see CLAUDE.md for the agreement that
# trivial L0/L1 use oracle (fastest), middle levels use A* with the
# smart heuristic, L4 uses the phased hybrid.
_LEVEL_PLANNER: Dict[int, str] = {
    0: "oracle",
    1: "oracle",
    2: "astar",
    3: "astar",
    4: "phased",
}

# Curriculum-spec presets — modest counts for the first cut.
_CURRICULA: Dict[str, List[Tuple[int, int]]] = {
    "train_120": [(0, 16), (1, 24), (2, 32), (3, 32), (4, 16)],
    "val_per_level": [(k, 6) for k in range(5)],
    "test_per_level": [(k, 6) for k in range(5)],
}


# ---------------------------------------------------------------------------
# Object roster — fixed for access-19 (18 blockers + 1 OoI).
# ---------------------------------------------------------------------------

_OBJECT_NAMES = [f"blocker_{i}" for i in range(18)] + ["ooi"]


# ---------------------------------------------------------------------------
# PDDL writers
# ---------------------------------------------------------------------------


def _enumerate_static_init(workspace) -> Tuple[List[str], List[str]]:
    """Return ``(object_names, static_init_predicates)`` for the PDDL :init.

    The access-19 PDDL domain has no static adjacency predicates
    (filter-mode pick/put have only dynamic preconditions), so the
    only "static" thing is the set of objects.  We still emit the
    function for parity with mlb's API.
    """
    cells: List[str] = []
    for region_name in workspace.regions:
        region = workspace[region_name]
        for cell in region.cells():
            cells.append(cell.id)
    objects = list(_OBJECT_NAMES) + cells
    return objects, []


def write_pddl_problem(
    template: Template,
    workspace,
    output_path: Path,
    problem_name: str,
) -> None:
    """Write a PDDL problem file matching the access-19 domain.

    Sections:
      :objects     — every cell + every movable.
      :init        — (occupied cell obj) for each source placement,
                     (empty cell) for the rest, (gripper-empty).
      :goal        — conjunction of (occupied cell obj) over the
                     template's goal_placements.
    """
    cell_names: List[str] = []
    for region_name in workspace.regions:
        region = workspace[region_name]
        for cell in region.cells():
            cell_names.append(cell.id)

    src_layout = template_source_layout(template)
    goal_atoms: List[str] = []
    for obj, cid in template.goal_placements:
        goal_atoms.append(f"(occupied {cid} {obj})")

    occupied_cells = set(src_layout.values())
    init: List[str] = []
    for obj, cid in template.source_placements:
        init.append(f"(occupied {cid} {obj})")
    for c in cell_names:
        if c not in occupied_cells:
            init.append(f"(empty {c})")
    init.append("(gripper-empty)")

    lines: List[str] = []
    lines.append(f"(define (problem {problem_name})")
    lines.append("  (:domain tabletop-access)")
    lines.append("  (:objects")
    lines.append(f"    {' '.join(_OBJECT_NAMES)} - movable")
    lines.append(f"    {' '.join(cell_names)} - cell")
    lines.append("  )")
    lines.append("  (:init")
    for p in init:
        lines.append(f"    {p}")
    lines.append("  )")
    lines.append("  (:goal (and")
    for a in goal_atoms:
        lines.append(f"    {a}")
    lines.append("  ))")
    lines.append(")")
    output_path.write_text("\n".join(lines) + "\n")


def write_plan_file(
    plan: List[Tuple],
    output_path: Path,
    metadata: Dict[str, Any],
) -> None:
    """Write a .pddl.plan file with one action per line + metadata trailer."""
    lines = []
    for action in plan:
        lines.append("(" + " ".join(str(a) for a in action) + ")")
    lines.append(f"; cost = {len(plan)} (unit cost)")
    for k, v in metadata.items():
        lines.append(f"; {k}: {v}")
    output_path.write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _state_from_layout(layout: Dict[str, str]) -> Dict[Tuple, bool]:
    """Build the ground-state dict needed by ``restore_state``."""
    return _layout_to_state(layout, held=None)


def _setup_env(scratch_dir: Path):
    """Build env + chains + executor + home pose for a worker."""
    builder, ws, cfg = make_access19_builder(scratch_dir=scratch_dir)
    env = builder.build_env(rate=10000.0)
    apply_runtime_tweaks(env, cfg)
    cube_half = float(env.get_object_half_size("ooi")[2])
    table_z = ws["shelf_interior"].level_z - cube_half
    executor = _build_executor(env, table_z=table_z,
                                       allowed_types=[GraspType.FRONT])
    shelf_home = _solve_access19_staging(env, ws, cfg)
    lik = LinearIKPlanner(env, n_substeps=12, joint_check_steps=8)
    pick_fn = make_access19_pick_fn(env, executor, ws, cfg,
                                            cube_half_z=cube_half, lik=lik)
    put_fn = make_access19_put_fn(env, executor, ws, cfg,
                                          cube_half_z=cube_half, lik=lik)
    return env, ws, cfg, executor, pick_fn, put_fn, shelf_home


# ---------------------------------------------------------------------------
# Plan generation
# ---------------------------------------------------------------------------


def build_plan(
    template: Template,
    env, workspace, cfg,
    executor, pick_fn, put_fn, home_qpos,
    *,
    planner_kind: str,
    time_budget_s: float = 180.0,
) -> Tuple[List[Tuple], Dict[str, Any]]:
    """Dispatch to the right planner for this template/level combination.

    Returns ``(plan, info)`` where ``plan`` is the action sequence and
    ``info`` carries planner-level diagnostics for the meta JSON.
    """
    init_layout = template_source_layout(template)
    goal = template_goal_layout(template)

    if planner_kind == "oracle":
        # OoI-only goal — extract goal cell for OoI.
        if "ooi" not in goal:
            raise ValueError("oracle_plan needs an OoI goal cell")
        goal_cell = Cell.parse(goal["ooi"])
        res = oracle_plan(
            env, workspace, cfg, init_layout, goal_cell, _OBJECT_NAMES,
            pick_fn, put_fn,
            executor=executor, home_qpos=home_qpos, fast=True,
            max_actions=200, max_backtrack=64,
        )
    elif planner_kind == "astar":
        res = astar_plan(
            env, workspace, cfg, init_layout, goal, _OBJECT_NAMES,
            pick_fn, put_fn,
            executor=executor, home_qpos=home_qpos, fast=True,
            max_states=10000, time_budget_s=time_budget_s,
        )
    elif planner_kind == "phased":
        res = phased_plan(
            env, workspace, cfg, init_layout, goal, _OBJECT_NAMES,
            pick_fn, put_fn,
            executor=executor, home_qpos=home_qpos, fast=True,
            phase2_time_budget_s=time_budget_s,
            phase2_max_states=30000,
        )
    else:
        raise ValueError(f"unknown planner_kind {planner_kind!r}")

    info = {
        "planner": planner_kind,
        "success": res.success,
        "plan_len": len(res.plan),
        "n_feasibility_checks": res.n_feasibility_checks,
        "planner_elapsed_s": f"{res.elapsed_s:.2f}",
    }
    return list(res.plan), info


def _sample_template(
    rng: np.random.Generator,
    *,
    level: int,
) -> Template:
    """Sample a template suited to the given curriculum level.

    Always selects from ``_LEVEL_TEMPLATE_NAMES[level]``.  Applies a
    random mirror_x with prob=0.5 for variant multiplication.
    """
    name = str(rng.choice(_LEVEL_TEMPLATE_NAMES[level]))
    return_blockers = level >= 2

    if name == "front_row_subset":
        n = int(rng.integers(0, 2)) if level == 0 \
                else int(rng.integers(2, 4))
        tpl = front_row_subset(n, rng, return_blockers=return_blockers)
    elif name == "dense_front":
        n_rows = int(rng.integers(1, 3))    # 1 or 2 rows
        tpl = dense_front(n_rows, rng, return_blockers=return_blockers)
    elif name == "scattered_subset":
        n = int(rng.integers(3, 7))         # 3..6 scattered blockers
        tpl = scattered_subset(n, rng, return_blockers=return_blockers)
    elif name == "gotcha_corridor_jam":
        tpl = gotcha_corridor_jam(rng, return_blockers=True)
    elif name == "canonical_18":
        tpl = canonical_18(return_blockers=True)
    else:
        raise ValueError(f"unknown template name {name!r}")

    if bool(rng.integers(0, 2)):
        try:
            tpl = mirror_x(tpl)
        except Exception:
            pass        # mirror failed (e.g., collision); use original
    return tpl


# ---------------------------------------------------------------------------
# Per-instance runner
# ---------------------------------------------------------------------------


def _generate_one(
    config_num: int,
    rng: np.random.Generator,
    args,
    env, workspace, cfg,
    executor, pick_fn, put_fn, home_qpos,
    output_dir: Path,
    split: str,
    *,
    level: int,
    level_subdir: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Generate a single access-19 instance for the given curriculum level."""
    template = _sample_template(rng, level=level)
    planner_kind = _LEVEL_PLANNER[level]

    plan, info = build_plan(
        template, env, workspace, cfg,
        executor, pick_fn, put_fn, home_qpos,
        planner_kind=planner_kind,
        time_budget_s=args.time_budget,
    )
    if not info["success"]:
        return None

    # Replay-validate via FAST.
    init_state = _state_from_layout(template_source_layout(template))
    seq_res = check_action_sequence(
        env, workspace, cfg, init_state, plan,
        _OBJECT_NAMES, pick_fn, put_fn,
        executor=executor, fast=True, home_qpos=home_qpos,
        short_circuit=True,
    )
    if not seq_res["success"]:
        return None

    if level_subdir is not None:
        problem_dir = output_dir / split / level_subdir
    else:
        problem_dir = output_dir / split
    problem_dir.mkdir(parents=True, exist_ok=True)

    problem_path = problem_dir / f"config_{config_num}.pddl"
    plan_path = problem_dir / f"config_{config_num}.pddl.plan"
    pn_sub = level_subdir + "-" if level_subdir else ""

    write_pddl_problem(
        template, workspace, problem_path,
        problem_name=f"access19-{split}-{pn_sub}{config_num}",
    )
    write_plan_file(plan, plan_path, metadata={
        "template": template.name,
        "level": level,
        "planner": planner_kind,
        "split": split,
        "config_num": config_num,
        "n_feasibility_checks": info["n_feasibility_checks"],
        "planner_elapsed_s": info["planner_elapsed_s"],
        "replay_elapsed_s": f"{seq_res['elapsed_s']:.2f}",
    })

    return {
        "template": template.name,
        "level": level,
        "planner": planner_kind,
        "plan_len": len(plan),
        "elapsed_s": seq_res["elapsed_s"],
        "config_num": config_num,
        "split": split,
    }


# ---------------------------------------------------------------------------
# Split runner (single-process)
# ---------------------------------------------------------------------------


def _init_stats() -> dict:
    return {
        "attempts": 0, "accepted": 0,
        "reject_plan_failed": 0,
        "templates": Counter(),
        "plan_len_hist": Counter(),
        "gen_seconds": [],
    }


def _generate_split(
    split: str,
    count: int,
    args,
    output_base: Path,
    seed: int,
    *,
    level: int,
    level_subdir: Optional[str] = None,
    config_offset: int = 0,
) -> dict:
    """Single-process split runner."""
    if count <= 0:
        return _init_stats()
    rng = np.random.default_rng(seed)
    with tempfile.TemporaryDirectory(prefix="access19_data_") as td:
        env, ws, cfg, executor, pick_fn, put_fn, shelf_home = (
            _setup_env(Path(td))
        )
        stats = _init_stats()
        t_start = time.time()
        config_num = config_offset
        max_attempts = count * 30
        while stats["accepted"] < count and stats["attempts"] < max_attempts:
            stats["attempts"] += 1
            config_num += 1
            try:
                res = _generate_one(
                    config_num, rng, args, env, ws, cfg,
                    executor, pick_fn, put_fn, shelf_home,
                    output_base, split,
                    level=level, level_subdir=level_subdir,
                )
            except Exception as exc:
                stats["reject_plan_failed"] += 1
                if args.verbose:
                    print(f"  [{split}] L{level} attempt {stats['attempts']} "
                              f"raised {type(exc).__name__}: {exc}")
                continue
            if res is None:
                stats["reject_plan_failed"] += 1
                continue

            stats["accepted"] += 1
            stats["templates"][res["template"]] += 1
            stats["plan_len_hist"][res["plan_len"]] += 1
            stats["gen_seconds"].append(res["elapsed_s"])

            if stats["accepted"] % 5 == 0 or stats["accepted"] == 1:
                elapsed = time.time() - t_start
                eta = elapsed / stats["accepted"] * (count - stats["accepted"])
                print(f"  [{split}] L{level} {stats['accepted']}/{count}  "
                          f"plan_len={res['plan_len']}  "
                          f"elapsed={elapsed:.0f}s  eta={eta:.0f}s  "
                          f"accept={stats['accepted']}/{stats['attempts']}")
    return stats


# ---------------------------------------------------------------------------
# Parallel worker
# ---------------------------------------------------------------------------


def _worker(worker_id: int, split: str, start_idx: int, count: int,
                 args, output_base_str: str, seed: int,
                 level: int,
                 level_subdir: Optional[str] = None) -> Tuple[dict, list]:
    """One worker process: generates ``count`` instances at the given level."""
    rng = np.random.default_rng(seed + worker_id * 9999)
    output_base = Path(output_base_str)
    with tempfile.TemporaryDirectory(prefix="access19_data_") as td:
        env, ws, cfg, executor, pick_fn, put_fn, shelf_home = (
            _setup_env(Path(td))
        )
        stats = _init_stats()
        config_num = start_idx
        max_attempts = count * 30
        while stats["accepted"] < count and stats["attempts"] < max_attempts:
            stats["attempts"] += 1
            try:
                res = _generate_one(
                    config_num, rng, args, env, ws, cfg, executor,
                    pick_fn, put_fn, shelf_home,
                    output_base, split,
                    level=level, level_subdir=level_subdir,
                )
            except Exception:
                stats["reject_plan_failed"] += 1
                continue
            if res is None:
                stats["reject_plan_failed"] += 1
                continue
            stats["accepted"] += 1
            stats["templates"][res["template"]] += 1
            stats["plan_len_hist"][res["plan_len"]] += 1
            stats["gen_seconds"].append(res["elapsed_s"])
            config_num += 1
    return stats, []


def _generate_split_parallel(
    split: str, count: int, args,
    output_base: Path, seed: int,
    *,
    level: int,
    level_subdir: Optional[str] = None,
    config_offset: int = 0,
) -> dict:
    """Distribute the split across ``args.num_workers`` workers."""
    if args.num_workers <= 1:
        return _generate_split(split, count, args, output_base, seed,
                                       level=level, level_subdir=level_subdir,
                                       config_offset=config_offset)

    counts = [count // args.num_workers] * args.num_workers
    for i in range(count % args.num_workers):
        counts[i] += 1
    start_idxs = [config_offset + 1 + sum(counts[:i])
                          for i in range(args.num_workers)]

    ctx = mp.get_context("spawn")
    futures = []
    with ctx.Pool(args.num_workers) as pool:
        for wid in range(args.num_workers):
            if counts[wid] == 0:
                continue
            args_tuple = (wid, split, start_idxs[wid], counts[wid],
                              args, str(output_base), seed,
                              level, level_subdir)
            futures.append(pool.apply_async(_worker, args_tuple))
        worker_results = [fut.get() for fut in futures]

    agg = _init_stats()
    for stats, _render in worker_results:
        agg["attempts"] += stats["attempts"]
        agg["accepted"] += stats["accepted"]
        agg["reject_plan_failed"] += stats["reject_plan_failed"]
        agg["templates"].update(stats["templates"])
        agg["plan_len_hist"].update(stats["plan_len_hist"])
        agg["gen_seconds"].extend(stats["gen_seconds"])
    return agg


# ---------------------------------------------------------------------------
# Curriculum driver
# ---------------------------------------------------------------------------


def _print_stats(split: str, stats: dict, elapsed: float) -> None:
    accepted = stats["accepted"]
    if accepted == 0:
        print(f"\n=== {split} summary ===\n  no instances accepted")
        return
    print(f"\n=== {split} summary ===")
    print(f"  accepted/attempts: {accepted}/{stats['attempts']}")
    print(f"  reject rate: {100 * (1 - accepted/stats['attempts']):.1f}%")
    print(f"  elapsed: {elapsed:.1f}s")
    if stats["gen_seconds"]:
        print(f"  mean gen time: "
                  f"{sum(stats['gen_seconds'])/len(stats['gen_seconds']):.2f}s")
    print(f"  templates: {dict(stats['templates'])}")
    print(f"  plan length distribution: "
              f"{dict(sorted(stats['plan_len_hist'].items()))}")


def _run_curriculum(
    split: str,
    spec: List[Tuple[int, int]],
    args,
    output_base: Path,
    seed: int,
) -> dict:
    """Run a curriculum spec — list of ``(level, count)`` tuples.

    Each level's instances go to ``<output_base>/<split>/L<level>/``.
    """
    overall = _init_stats()
    t_start = time.time()
    offset_per_level = 0
    for level, count in spec:
        print(f"\n[curriculum] {split} L{level}: {count} instances")
        level_subdir = f"L{level}"
        stats = _generate_split_parallel(
            split, count, args, output_base, seed + level * 7,
            level=level, level_subdir=level_subdir,
            config_offset=offset_per_level,
        )
        overall["attempts"] += stats["attempts"]
        overall["accepted"] += stats["accepted"]
        overall["reject_plan_failed"] += stats["reject_plan_failed"]
        overall["templates"].update(stats["templates"])
        overall["plan_len_hist"].update(stats["plan_len_hist"])
        overall["gen_seconds"].extend(stats["gen_seconds"])
        offset_per_level += count
    _print_stats(split, overall, time.time() - t_start)
    return overall


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _copy_domain(output_dir: Path) -> None:
    if _DOMAIN.exists():
        shutil.copy(_DOMAIN, output_dir / "domain.pddl")


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate access-19 PDDL instances + reference plans"
    )
    p.add_argument("--output-dir", type=Path, default=_DEFAULT_OUTPUT_DIR)
    p.add_argument("--num-train", type=int, default=_DEFAULT_TRAIN)
    p.add_argument("--num-val", type=int, default=_DEFAULT_VAL)
    p.add_argument("--num-test", type=int, default=_DEFAULT_TEST)
    p.add_argument("--num-workers", type=int, default=_DEFAULT_NUM_WORKERS)
    p.add_argument("--seed", type=int, default=_DEFAULT_SEED)
    p.add_argument("--time-budget", type=float, default=180.0,
                          help="per-instance planner time budget (s)")
    p.add_argument("--curriculum-spec", choices=list(_CURRICULA.keys()),
                          default=None,
                          help="if set, ignores --num-train and runs a "
                                   "curriculum preset")
    p.add_argument("--level", type=int, default=None,
                          help="run only this level (combine with --num + "
                                   "--split for shell-driver dispatch)")
    p.add_argument("--num", type=int, default=None,
                          help="instances when --level is set")
    p.add_argument("--split", default="train",
                          help="which split to write into when --level is set")
    p.add_argument("--config-offset", type=int, default=0,
                          help="starting config number (for shell-driver "
                                   "dispatch across processes)")
    p.add_argument("--no-domain-copy", action="store_true",
                          help="don't copy domain.pddl to output_dir")
    p.add_argument("--verbose", action="store_true")
    args = p.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    if not args.no_domain_copy:
        _copy_domain(args.output_dir)

    # Per-level shell-driver mode.
    if args.level is not None:
        if args.num is None:
            print("--level requires --num", flush=True)
            return 2
        level_subdir = f"L{args.level}"
        stats = _generate_split_parallel(
            args.split, args.num, args, args.output_dir, args.seed,
            level=args.level, level_subdir=level_subdir,
            config_offset=args.config_offset,
        )
        _print_stats(f"{args.split}/L{args.level}", stats, 0.0)
        return 0

    # Curriculum-spec mode.
    if args.curriculum_spec is not None:
        spec = _CURRICULA[args.curriculum_spec]
        _run_curriculum("train", spec, args, args.output_dir, args.seed)
        if args.num_val > 0:
            _run_curriculum("val", _CURRICULA["val_per_level"],
                                  args, args.output_dir, args.seed + 100)
        if args.num_test > 0:
            _run_curriculum("test", _CURRICULA["test_per_level"],
                                  args, args.output_dir, args.seed + 200)
        return 0

    print("Specify --curriculum-spec or (--level + --num).", flush=True)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
