"""access-19 dataset generation — PDDL problems with feasibility validation.

Mirrors :mod:`tampanda.symbolic.domains.multilevel_blocks.generate_data`:

1. A template is sampled (front_row_subset / dense_front /
   scattered_subset / gotcha_corridor_jam / canonical_18, with mirror
   ops applied to half the instances).
2. The initial layout + goal layout are derived from the template.
3. A plan is generated by the search planner — :func:`oracle_plan` for
   OoI-only goals, :func:`astar_plan` for return goals at L1-L3,
   :func:`phased_plan` for L4-scale return goals.
4. The full action sequence is replayed through
   :func:`check_action_sequence` (FAST mode) and rejected if any
   action fails.  This is the same FAST↔FULL agreement contract used
   by ``access19_feasibility_smoke.py``.
5. PDDL problem + plan + meta are written to disk.

Output layout::

    data/access19/
    ├── domain.pddl
    ├── train/
    │   ├── L0/config_1.pddl
    │   ├── L0/config_1.pddl.plan
    │   └── ...
    ├── test/
    └── val/

Usage::

    python -m tampanda.symbolic.domains.access19.generate_data \\
        --curriculum-spec train_120 --num-workers 4 \\
        --output-dir data/access19

    python -m tampanda.symbolic.domains.access19.generate_data \\
        --level 2 --num 30 --split val \\
        --output-dir data/access19
"""
from __future__ import annotations

import argparse
import multiprocessing as mp
import shutil
import tempfile
import time
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

from tampanda.symbolic.domains.access19 import (
    apply_runtime_tweaks, make_access19_builder,
    make_access19_pick_fn, make_access19_put_fn,
)
from tampanda.symbolic.domains.access19.feasibility import (
    check_action_sequence,
)
from tampanda.symbolic.domains.access19.parallel import _layout_to_state
from tampanda.symbolic.domains.access19.planner import (
    astar_plan, oracle_plan, phased_plan,
)
from tampanda.symbolic.domains.access19.reachability import (
    _build_executor, _solve_access19_staging,
)
from tampanda.symbolic.domains.access19.templates import (
    Template,
    canonical_12,
    canonical_18,
    dense_front,
    dense_front_n,
    easy_l0,
    front_row_subset,
    goal_layout as template_goal_layout,
    gotcha_corridor_jam,
    mirror_x,
    scattered_subset,
    source_layout as template_source_layout,
)
from tampanda.symbolic.workspace import Cell
from tampanda.planners.grasp_planner import GraspType
from tampanda.planners.linear_ik import LinearIKPlanner


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_HERE = Path(__file__).parent
_DOMAIN = (_HERE / "pddl" / "domain.pddl").resolve()
_DOMAIN_DERIVED = (_HERE / "pddl" / "domain_derived.pddl").resolve()

_DEFAULT_OUTPUT_DIR = Path("data/access19")
_DEFAULT_TRAIN = 24
_DEFAULT_VAL = 6
_DEFAULT_TEST = 6
_DEFAULT_NUM_WORKERS = 1
_DEFAULT_SEED = 42

# Templates allowed per level.  L0/L1 = OoI-only goal; L2+ = return-all
# goal (specified via the ``return_blockers`` kwarg in the sampler).
_LEVEL_TEMPLATE_NAMES: Dict[int, List[str]] = {
    0: ["front_row_subset", "easy_l0"],
    # easy_l0 adds varied OoI start (interior or deck) + random deck
    # goal + optional non-blocking blocker.  Mixed 50/50 with the
    # original back-row OoI front_row_subset n=0..1 pattern.
    1: ["front_row_subset"],     # n=2..3, return=False
    2: ["dense_front", "scattered_subset"],   # n_rows<=2 / n<=6, return=True
    3: ["dense_front", "scattered_subset", "gotcha_corridor_jam"],
    4: ["canonical_18"],         # 18 blockers, return=True (uses phased)
}

# Per-curriculum L4 template override.  Used by the v2 bundle to swap
# in ``canonical_12`` (Option-B training) while keeping the held-out
# evals at the original ``canonical_18`` distribution.
_L4_TEMPLATE_OVERRIDE: Dict[str, List[str]] = {
    # default: use the module-level _LEVEL_TEMPLATE_NAMES[4]
}

# Planner choice per level — see CLAUDE.md for the agreement that
# trivial L0/L1 use oracle (fastest), middle levels use A* with the
# smart heuristic, L4 uses the phased hybrid.
_LEVEL_PLANNER: Dict[int, str] = {
    0: "oracle",
    1: "oracle",
    2: "astar",
    3: "astar",
    4: "phased",
}

# Curriculum-spec presets.
_CURRICULA: Dict[str, List[Tuple[int, int]]] = {
    "train_120": [(0, 16), (1, 24), (2, 32), (3, 32), (4, 16)],
    "val_per_level": [(k, 6) for k in range(5)],
    "test_per_level": [(k, 6) for k in range(5)],
    # Option-B (max-12-blocker) training distribution.  L4 = canonical_12.
    "train_300_option_b": [(0, 40), (1, 60), (2, 80), (3, 80), (4, 40)],
    "val_50_option_b":    [(0, 10), (1, 10), (2, 10), (3, 10), (4, 10)],
    # v4: max-14-blocker training with mixed 50% return at L3+L4.
    # L4 = dense_front_n(n ∈ [10, 14]).  L3 = dense_front (n_rows
    # 3..4 → 9..12 blockers).
    "train_600_v4":       [(0, 80), (1, 120), (2, 160), (3, 160), (4, 80)],
    "val_100_v4":         [(0, 20), (1, 20), (2, 20), (3, 20), (4, 20)],
    # v4.5: focused on the access-19 target distribution.  No curriculum
    # tiers — every problem is L4 with dense_front_n(n ∈ [3, 18])
    # and 100% return.  Val biases half to canonical_18.
    "train_600_v4_5":     [(4, 600)],
    "val_10_v4_5":        [(4, 10)],
    # Held-out evals (unchanged from v3).
    "eval_30_pre_b":      [(k, 6) for k in range(5)],
    "eval_30_full_a19":   [(4, 30)],
}
_L4_TEMPLATE_OVERRIDE = {
    "train_300_option_b":  ["canonical_12"],
    "val_50_option_b":     ["canonical_12"],
    "train_600_v4":        ["dense_front_n"],
    "val_100_v4":          ["dense_front_n"],
    "train_600_v4_5":      ["dense_front_n"],
    "val_10_v4_5":         ["dense_front_n"],
    "eval_30_pre_b":       ["canonical_18"],
    "eval_30_full_a19":    ["canonical_18"],
}

# v4: per-curriculum, per-level return probability.  ``None`` =
# fall back to the historical hard-coded ``level >= 2`` boolean.
_RETURN_PROB: Dict[str, Dict[int, float]] = {
    "train_600_v4": {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.5, 4: 0.5},
    "val_100_v4":   {0: 0.0, 1: 0.0, 2: 0.0, 3: 0.5, 4: 0.5},
    # v4.5: 100% return at all positions (focused on access-19 target).
    "train_600_v4_5": {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0, 4: 1.0},
    "val_10_v4_5":    {0: 1.0, 1: 1.0, 2: 1.0, 3: 1.0, 4: 1.0},
}

# v4: L4 n_blockers range (used when sampler dispatches dense_front_n).
_L4_N_BLOCKERS_RANGE: Tuple[int, int] = (10, 14)   # inclusive bounds
# Per-curriculum override of the L4 n_blockers range.  Falls back to
# ``_L4_N_BLOCKERS_RANGE`` when no entry.
_L4_N_BLOCKERS_RANGE_OVERRIDE: Dict[str, Tuple[int, int]] = {
    "train_600_v4_5": (3, 18),
    "val_10_v4_5":    (3, 17),   # 50% will be canonical_18 via bias
}
# Per-curriculum probability of using n=18 (canonical_18 pattern)
# regardless of the range above.  Used to bias the v4.5 val set
# toward the canonical configuration.
_L4_CANONICAL_18_BIAS: Dict[str, float] = {
    "val_10_v4_5": 0.5,
}


# ---------------------------------------------------------------------------
# Object roster — fixed for access-19 (18 blockers + 1 OoI).
# ---------------------------------------------------------------------------

_OBJECT_NAMES = [f"blocker_{i}" for i in range(18)] + ["ooi"]


# ---------------------------------------------------------------------------
# PDDL writers
# ---------------------------------------------------------------------------


# Cube columns in shelf_interior where blockers and the OoI live.
# Used by ``_same_column_front_facts`` to scope the static
# ``(same-column-front …)`` emission to the relevant axis.
_CUBE_COLS_IX: Tuple[int, ...] = (1, 3, 5)


def _same_column_front_facts(workspace) -> List[str]:
    """Emit ``(same-column-front ?cf ?cb)`` for every ordered pair
    (cf, cb) of cells in the same cube column of ``shelf_interior``
    with ``cf.iy < cb.iy``.

    Only the 3 cube columns (``ix ∈ {1, 3, 5}``) are emitted —
    blockers and the OoI live there exclusively in access-19's
    canonical layouts.  21 ordered pairs per column × 3 columns = 63
    facts per problem.

    The ``shelf_top`` grid is open from above (the chain enters
    via the open ceiling, not via a -y face), so the "front" axis
    has no analog there — no same-column-front facts on the deck.
    """
    facts: List[str] = []
    region = workspace["shelf_interior"]
    ny = region.cells_y
    for ix in _CUBE_COLS_IX:
        for iy_front in range(ny):
            if region.is_excluded(ix, iy_front):
                continue
            for iy_back in range(iy_front + 1, ny):
                if region.is_excluded(ix, iy_back):
                    continue
                cf = f"shelf_interior__{ix}_{iy_front}"
                cb = f"shelf_interior__{ix}_{iy_back}"
                facts.append(f"(same-column-front {cf} {cb})")
    return facts


def _enumerate_static_init(workspace) -> Tuple[List[str], List[str]]:
    """Return ``(object_names, static_init_predicates)`` for the PDDL :init.

    Static facts = per-grid ``(adjacent north c1 c2)`` and
    ``(adjacent east c1 c2)`` edges + ``(same-column-front …)`` for
    cube columns of ``shelf_interior``.  Each grid is internally
    8-connected only through its own cells; there is no adjacency
    between ``shelf_interior`` and ``shelf_top``.  Convention:
    ``north`` = +iy (depth, away from robot), ``east`` = +ix
    (column index, robot's right).
    """
    cells: List[str] = []
    adjacencies: List[str] = []
    for region_name in workspace.regions:
        region = workspace[region_name]
        for cell in region.cells():
            cells.append(cell.id)
        # Adjacency edges within this grid only.
        from tampanda.symbolic.workspace import GridRegion
        if not isinstance(region, GridRegion):
            continue
        nx, ny = region.cells_x, region.cells_y
        for ix in range(nx):
            for iy in range(ny):
                if region.is_excluded(ix, iy):
                    continue
                here = f"{region.name}__{ix}_{iy}"
                if iy + 1 < ny and not region.is_excluded(ix, iy + 1):
                    north_nb = f"{region.name}__{ix}_{iy + 1}"
                    adjacencies.append(f"(adjacent north {here} {north_nb})")
                if ix + 1 < nx and not region.is_excluded(ix + 1, iy):
                    east_nb = f"{region.name}__{ix + 1}_{iy}"
                    adjacencies.append(f"(adjacent east {here} {east_nb})")
    statics = adjacencies + _same_column_front_facts(workspace)
    objects = list(_OBJECT_NAMES) + cells
    return objects, statics


def write_pddl_problem(
    template: Template,
    workspace,
    output_path: Path,
    problem_name: str,
) -> None:
    """Write a PDDL problem file matching the access-19 domain.

    Sections:
      :objects     — every cell + every movable.
      :init        — (occupied cell obj) for each source placement,
                     (empty cell) for the rest, (gripper-empty).
      :goal        — conjunction of (occupied cell obj) over the
                     template's goal_placements.
    """
    _, static_adjacencies = _enumerate_static_init(workspace)
    cell_names: List[str] = []
    for region_name in workspace.regions:
        region = workspace[region_name]
        for cell in region.cells():
            cell_names.append(cell.id)

    src_layout = template_source_layout(template)
    goal_atoms: List[str] = []
    for obj, cid in template.goal_placements:
        goal_atoms.append(f"(occupied {cid} {obj})")

    # Active object roster — only movables that appear in source or
    # goal placements.  Declaring unused movables in ``:objects`` would
    # add isolated nodes to the GNN's predicate graph (no incident
    # edges, no embedding signal) and degrade learning.  Unused
    # bodies still exist in MuJoCo but are parked off-scene by
    # ``restore_state``; symbolically they're absent.
    active_movables: List[str] = []
    seen = set()
    for obj, _ in template.source_placements:
        if obj not in seen:
            seen.add(obj)
            active_movables.append(obj)
    for obj, _ in template.goal_placements:
        if obj not in seen:
            seen.add(obj)
            active_movables.append(obj)

    occupied_cells = set(src_layout.values())
    init: List[str] = []
    init.extend(static_adjacencies)
    for obj, cid in template.source_placements:
        init.append(f"(occupied {cid} {obj})")
    for c in cell_names:
        if c not in occupied_cells:
            init.append(f"(empty {c})")
    init.append("(gripper-empty)")

    lines: List[str] = []
    lines.append(f"(define (problem {problem_name})")
    lines.append("  (:domain tabletop-access)")
    lines.append("  (:objects")
    lines.append(f"    {' '.join(active_movables)} - movable")
    lines.append(f"    {' '.join(cell_names)} - cell")
    lines.append("  )")
    lines.append("  (:init")
    for p in init:
        lines.append(f"    {p}")
    lines.append("  )")
    lines.append("  (:goal (and")
    for a in goal_atoms:
        lines.append(f"    {a}")
    lines.append("  ))")
    lines.append(")")
    output_path.write_text("\n".join(lines) + "\n")


def write_plan_file(
    plan: List[Tuple],
    output_path: Path,
    metadata: Dict[str, Any],
) -> None:
    """Write a .pddl.plan file with one action per line + metadata trailer."""
    lines = []
    for action in plan:
        lines.append("(" + " ".join(str(a) for a in action) + ")")
    lines.append(f"; cost = {len(plan)} (unit cost)")
    for k, v in metadata.items():
        lines.append(f"; {k}: {v}")
    output_path.write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _state_from_layout(layout: Dict[str, str]) -> Dict[Tuple, bool]:
    """Build the ground-state dict needed by ``restore_state``."""
    return _layout_to_state(layout, held=None)


def _setup_env(scratch_dir: Path):
    """Build env + chains + executor + home pose for a worker."""
    builder, ws, cfg = make_access19_builder(scratch_dir=scratch_dir)
    env = builder.build_env(rate=10000.0)
    apply_runtime_tweaks(env, cfg)
    cube_half = float(env.get_object_half_size("ooi")[2])
    table_z = ws["shelf_interior"].level_z - cube_half
    executor = _build_executor(env, table_z=table_z,
                                       allowed_types=[GraspType.FRONT])
    shelf_home = _solve_access19_staging(env, ws, cfg)
    lik = LinearIKPlanner(env, n_substeps=12, joint_check_steps=8)
    pick_fn = make_access19_pick_fn(env, executor, ws, cfg,
                                            cube_half_z=cube_half, lik=lik,
                                            home_qpos=shelf_home)
    put_fn = make_access19_put_fn(env, executor, ws, cfg,
                                          cube_half_z=cube_half, lik=lik,
                                          home_qpos=shelf_home)
    return env, ws, cfg, executor, pick_fn, put_fn, shelf_home


# ---------------------------------------------------------------------------
# Plan generation
# ---------------------------------------------------------------------------


def build_plan(
    template: Template,
    env, workspace, cfg,
    executor, pick_fn, put_fn, home_qpos,
    *,
    planner_kind: str,
    time_budget_s: float = 180.0,
) -> Tuple[List[Tuple], Dict[str, Any]]:
    """Dispatch to the right planner for this template/level combination.

    Returns ``(plan, info)`` where ``plan`` is the action sequence and
    ``info`` carries planner-level diagnostics for the meta JSON.
    """
    init_layout = template_source_layout(template)
    goal = template_goal_layout(template)

    if planner_kind == "oracle":
        # OoI-only goal — extract goal cell for OoI.
        if "ooi" not in goal:
            raise ValueError("oracle_plan needs an OoI goal cell")
        goal_cell = Cell.parse(goal["ooi"])
        res = oracle_plan(
            env, workspace, cfg, init_layout, goal_cell, _OBJECT_NAMES,
            pick_fn, put_fn,
            executor=executor, home_qpos=home_qpos, fast=True,
            max_actions=200, max_backtrack=64,
        )
    elif planner_kind == "astar":
        res = astar_plan(
            env, workspace, cfg, init_layout, goal, _OBJECT_NAMES,
            pick_fn, put_fn,
            executor=executor, home_qpos=home_qpos, fast=True,
            max_states=10000, time_budget_s=time_budget_s,
        )
    elif planner_kind == "phased":
        res = phased_plan(
            env, workspace, cfg, init_layout, goal, _OBJECT_NAMES,
            pick_fn, put_fn,
            executor=executor, home_qpos=home_qpos, fast=True,
            phase2_time_budget_s=time_budget_s,
            phase2_max_states=30000,
        )
    else:
        raise ValueError(f"unknown planner_kind {planner_kind!r}")

    info = {
        "planner": planner_kind,
        "success": res.success,
        "plan_len": len(res.plan),
        "n_feasibility_checks": res.n_feasibility_checks,
        "planner_elapsed_s": f"{res.elapsed_s:.2f}",
    }
    return list(res.plan), info


def _sample_template(
    rng: np.random.Generator,
    *,
    level: int,
    curriculum_spec: Optional[str] = None,
) -> Template:
    """Sample a template suited to the given curriculum level.

    Selects from ``_LEVEL_TEMPLATE_NAMES[level]``, with a per-
    curriculum override for L4 (used by the v2 bundle to swap
    ``canonical_18`` ↔ ``canonical_12``).  Applies a random mirror_x
    with prob=0.5 for variant multiplication.

    Return-blocker behaviour: v3 and earlier hard-coded
    ``return_blockers = level >= 2``.  v4 uses per-curriculum
    per-level probabilities (see ``_RETURN_PROB``) so training can
    mix return vs no-return at the same level.
    """
    if (level == 4 and curriculum_spec is not None
            and curriculum_spec in _L4_TEMPLATE_OVERRIDE):
        names = _L4_TEMPLATE_OVERRIDE[curriculum_spec]
    else:
        names = _LEVEL_TEMPLATE_NAMES[level]
    name = str(rng.choice(names))

    # Per-curriculum return probability, falling back to the legacy
    # boolean for curricula that don't specify it.
    prob_table = _RETURN_PROB.get(curriculum_spec or "")
    if prob_table is not None:
        return_blockers = bool(rng.random() < prob_table.get(level, 0.0))
    else:
        return_blockers = level >= 2

    if name == "front_row_subset":
        n = int(rng.integers(0, 2)) if level == 0 \
                else int(rng.integers(2, 4))
        tpl = front_row_subset(n, rng, return_blockers=return_blockers)
    elif name == "dense_front":
        n_rows = int(rng.integers(1, 3))    # 1 or 2 rows
        tpl = dense_front(n_rows, rng, return_blockers=return_blockers)
    elif name == "dense_front_n":
        # Per-curriculum range + optional canonical-18 bias (v4.5 val).
        bias = _L4_CANONICAL_18_BIAS.get(curriculum_spec or "", 0.0)
        if bias > 0.0 and rng.random() < bias:
            n_blockers = 18
        else:
            lo, hi = _L4_N_BLOCKERS_RANGE_OVERRIDE.get(
                curriculum_spec or "", _L4_N_BLOCKERS_RANGE)
            n_blockers = int(rng.integers(lo, hi + 1))
        tpl = dense_front_n(n_blockers, rng,
                                  return_blockers=return_blockers)
    elif name == "scattered_subset":
        n = int(rng.integers(3, 7))         # 3..6 scattered blockers
        tpl = scattered_subset(n, rng, return_blockers=return_blockers)
    elif name == "gotcha_corridor_jam":
        tpl = gotcha_corridor_jam(rng, return_blockers=return_blockers)
    elif name == "canonical_18":
        tpl = canonical_18(return_blockers=True)
    elif name == "canonical_12":
        tpl = canonical_12(return_blockers=True)
    elif name == "easy_l0":
        tpl = easy_l0(rng)
    else:
        raise ValueError(f"unknown template name {name!r}")

    if bool(rng.integers(0, 2)):
        try:
            tpl = mirror_x(tpl)
        except Exception:
            pass        # mirror failed (e.g., collision); use original
    return tpl


# ---------------------------------------------------------------------------
# Per-instance runner
# ---------------------------------------------------------------------------


def _generate_one(
    config_num: int,
    rng: np.random.Generator,
    args,
    env, workspace, cfg,
    executor, pick_fn, put_fn, home_qpos,
    output_dir: Path,
    split: str,
    *,
    level: int,
    level_subdir: Optional[str] = None,
    curriculum_spec: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Generate a single access-19 instance for the given curriculum level."""
    template = _sample_template(rng, level=level,
                                        curriculum_spec=curriculum_spec)
    planner_kind = _LEVEL_PLANNER[level]

    plan, info = build_plan(
        template, env, workspace, cfg,
        executor, pick_fn, put_fn, home_qpos,
        planner_kind=planner_kind,
        time_budget_s=args.time_budget,
    )
    if not info["success"]:
        return None

    # Replay-validate via FAST.
    init_state = _state_from_layout(template_source_layout(template))
    seq_res = check_action_sequence(
        env, workspace, cfg, init_state, plan,
        _OBJECT_NAMES, pick_fn, put_fn,
        executor=executor, fast=True, home_qpos=home_qpos,
        short_circuit=True,
    )
    if not seq_res["success"]:
        return None

    if level_subdir is not None:
        problem_dir = output_dir / split / level_subdir
    else:
        problem_dir = output_dir / split
    problem_dir.mkdir(parents=True, exist_ok=True)

    problem_path = problem_dir / f"config_{config_num}.pddl"
    plan_path = problem_dir / f"config_{config_num}.pddl.plan"
    pn_sub = level_subdir + "-" if level_subdir else ""

    write_pddl_problem(
        template, workspace, problem_path,
        problem_name=f"access19-{split}-{pn_sub}{config_num}",
    )
    write_plan_file(plan, plan_path, metadata={
        "template": template.name,
        "level": level,
        "planner": planner_kind,
        "split": split,
        "config_num": config_num,
        "n_feasibility_checks": info["n_feasibility_checks"],
        "planner_elapsed_s": info["planner_elapsed_s"],
        "replay_elapsed_s": f"{seq_res['elapsed_s']:.2f}",
    })

    return {
        "template": template.name,
        "level": level,
        "planner": planner_kind,
        "plan_len": len(plan),
        "elapsed_s": seq_res["elapsed_s"],
        "config_num": config_num,
        "split": split,
    }


# ---------------------------------------------------------------------------
# Split runner (single-process)
# ---------------------------------------------------------------------------


def _init_stats() -> dict:
    return {
        "attempts": 0, "accepted": 0,
        "reject_plan_failed": 0,
        "templates": Counter(),
        "plan_len_hist": Counter(),
        "gen_seconds": [],
    }


def _generate_split(
    split: str,
    count: int,
    args,
    output_base: Path,
    seed: int,
    *,
    level: int,
    level_subdir: Optional[str] = None,
    config_offset: int = 0,
    curriculum_spec: Optional[str] = None,
) -> dict:
    """Single-process split runner."""
    if count <= 0:
        return _init_stats()
    rng = np.random.default_rng(seed)
    with tempfile.TemporaryDirectory(prefix="access19_data_") as td:
        env, ws, cfg, executor, pick_fn, put_fn, shelf_home = (
            _setup_env(Path(td))
        )
        stats = _init_stats()
        t_start = time.time()
        config_num = config_offset
        max_attempts = count * 30
        while stats["accepted"] < count and stats["attempts"] < max_attempts:
            stats["attempts"] += 1
            config_num += 1
            try:
                res = _generate_one(
                    config_num, rng, args, env, ws, cfg,
                    executor, pick_fn, put_fn, shelf_home,
                    output_base, split,
                    level=level, level_subdir=level_subdir,
                    curriculum_spec=curriculum_spec,
                )
            except Exception as exc:
                stats["reject_plan_failed"] += 1
                if args.verbose:
                    print(f"  [{split}] L{level} attempt {stats['attempts']} "
                              f"raised {type(exc).__name__}: {exc}")
                continue
            if res is None:
                stats["reject_plan_failed"] += 1
                continue

            stats["accepted"] += 1
            stats["templates"][res["template"]] += 1
            stats["plan_len_hist"][res["plan_len"]] += 1
            stats["gen_seconds"].append(res["elapsed_s"])

            if stats["accepted"] % 5 == 0 or stats["accepted"] == 1:
                elapsed = time.time() - t_start
                eta = elapsed / stats["accepted"] * (count - stats["accepted"])
                print(f"  [{split}] L{level} {stats['accepted']}/{count}  "
                          f"plan_len={res['plan_len']}  "
                          f"elapsed={elapsed:.0f}s  eta={eta:.0f}s  "
                          f"accept={stats['accepted']}/{stats['attempts']}")
    return stats


# ---------------------------------------------------------------------------
# Parallel worker
# ---------------------------------------------------------------------------


def _worker(worker_id: int, split: str, start_idx: int, count: int,
                 args, output_base_str: str, seed: int,
                 level: int,
                 level_subdir: Optional[str] = None,
                 curriculum_spec: Optional[str] = None,
                 ) -> Tuple[dict, list]:
    """One worker process: generates ``count`` instances at the given level."""
    rng = np.random.default_rng(seed + worker_id * 9999)
    output_base = Path(output_base_str)
    with tempfile.TemporaryDirectory(prefix="access19_data_") as td:
        env, ws, cfg, executor, pick_fn, put_fn, shelf_home = (
            _setup_env(Path(td))
        )
        stats = _init_stats()
        config_num = start_idx
        max_attempts = count * 30
        while stats["accepted"] < count and stats["attempts"] < max_attempts:
            stats["attempts"] += 1
            try:
                res = _generate_one(
                    config_num, rng, args, env, ws, cfg, executor,
                    pick_fn, put_fn, shelf_home,
                    output_base, split,
                    level=level, level_subdir=level_subdir,
                    curriculum_spec=curriculum_spec,
                )
            except Exception:
                stats["reject_plan_failed"] += 1
                continue
            if res is None:
                stats["reject_plan_failed"] += 1
                continue
            stats["accepted"] += 1
            stats["templates"][res["template"]] += 1
            stats["plan_len_hist"][res["plan_len"]] += 1
            stats["gen_seconds"].append(res["elapsed_s"])
            config_num += 1
    return stats, []


def _generate_split_parallel(
    split: str, count: int, args,
    output_base: Path, seed: int,
    *,
    level: int,
    level_subdir: Optional[str] = None,
    config_offset: int = 0,
    curriculum_spec: Optional[str] = None,
) -> dict:
    """Distribute the split across ``args.num_workers`` workers."""
    if args.num_workers <= 1:
        return _generate_split(split, count, args, output_base, seed,
                                       level=level, level_subdir=level_subdir,
                                       config_offset=config_offset,
                                       curriculum_spec=curriculum_spec)

    counts = [count // args.num_workers] * args.num_workers
    for i in range(count % args.num_workers):
        counts[i] += 1
    start_idxs = [config_offset + 1 + sum(counts[:i])
                          for i in range(args.num_workers)]

    ctx = mp.get_context("spawn")
    futures = []
    with ctx.Pool(args.num_workers) as pool:
        for wid in range(args.num_workers):
            if counts[wid] == 0:
                continue
            args_tuple = (wid, split, start_idxs[wid], counts[wid],
                              args, str(output_base), seed,
                              level, level_subdir, curriculum_spec)
            futures.append(pool.apply_async(_worker, args_tuple))
        worker_results = [fut.get() for fut in futures]

    agg = _init_stats()
    for stats, _render in worker_results:
        agg["attempts"] += stats["attempts"]
        agg["accepted"] += stats["accepted"]
        agg["reject_plan_failed"] += stats["reject_plan_failed"]
        agg["templates"].update(stats["templates"])
        agg["plan_len_hist"].update(stats["plan_len_hist"])
        agg["gen_seconds"].extend(stats["gen_seconds"])
    return agg


# ---------------------------------------------------------------------------
# Curriculum driver
# ---------------------------------------------------------------------------


def _print_stats(split: str, stats: dict, elapsed: float) -> None:
    accepted = stats["accepted"]
    if accepted == 0:
        print(f"\n=== {split} summary ===\n  no instances accepted")
        return
    print(f"\n=== {split} summary ===")
    print(f"  accepted/attempts: {accepted}/{stats['attempts']}")
    print(f"  reject rate: {100 * (1 - accepted/stats['attempts']):.1f}%")
    print(f"  elapsed: {elapsed:.1f}s")
    if stats["gen_seconds"]:
        print(f"  mean gen time: "
                  f"{sum(stats['gen_seconds'])/len(stats['gen_seconds']):.2f}s")
    print(f"  templates: {dict(stats['templates'])}")
    print(f"  plan length distribution: "
              f"{dict(sorted(stats['plan_len_hist'].items()))}")


def _run_curriculum(
    split: str,
    spec: List[Tuple[int, int]],
    args,
    output_base: Path,
    seed: int,
    *,
    flat: bool = False,
    curriculum_spec: Optional[str] = None,
) -> dict:
    """Run a curriculum spec — list of ``(level, count)`` tuples.

    By default each level's instances go to
    ``<output_base>/<split>/L<level>/``.  If ``flat=True``, all
    instances go to ``<output_base>/<split>/`` (collapsed; level
    still recorded in the plan-file metadata).
    """
    overall = _init_stats()
    t_start = time.time()
    offset_per_level = 0
    for level, count in spec:
        print(f"\n[curriculum] {split} L{level}: {count} instances")
        level_subdir = None if flat else f"L{level}"
        stats = _generate_split_parallel(
            split, count, args, output_base, seed + level * 7,
            level=level, level_subdir=level_subdir,
            config_offset=offset_per_level,
            curriculum_spec=curriculum_spec,
        )
        overall["attempts"] += stats["attempts"]
        overall["accepted"] += stats["accepted"]
        overall["reject_plan_failed"] += stats["reject_plan_failed"]
        overall["templates"].update(stats["templates"])
        overall["plan_len_hist"].update(stats["plan_len_hist"])
        overall["gen_seconds"].extend(stats["gen_seconds"])
        offset_per_level += count
    _print_stats(split, overall, time.time() - t_start)
    return overall


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _copy_domain(output_dir: Path) -> None:
    if _DOMAIN.exists():
        shutil.copy(_DOMAIN, output_dir / "domain.pddl")
    # Bundle the rgnet/GNN variant alongside the planner domain.  The
    # planner uses ``domain.pddl`` (no derived predicates);
    # ``domain_derived.pddl`` carries ``(blocking …)`` derived from
    # the static ``(same-column-front …)`` facts emitted per problem.
    if _DOMAIN_DERIVED.exists():
        shutil.copy(_DOMAIN_DERIVED, output_dir / "domain_derived.pddl")


def main() -> int:
    p = argparse.ArgumentParser(
        description="Generate access-19 PDDL instances + reference plans"
    )
    p.add_argument("--output-dir", type=Path, default=_DEFAULT_OUTPUT_DIR)
    p.add_argument("--num-train", type=int, default=_DEFAULT_TRAIN)
    p.add_argument("--num-val", type=int, default=_DEFAULT_VAL)
    p.add_argument("--num-test", type=int, default=_DEFAULT_TEST)
    p.add_argument("--num-workers", type=int, default=_DEFAULT_NUM_WORKERS)
    p.add_argument("--seed", type=int, default=_DEFAULT_SEED)
    p.add_argument("--time-budget", type=float, default=180.0,
                          help="per-instance planner time budget (s)")
    p.add_argument("--curriculum-spec", choices=list(_CURRICULA.keys()),
                          default=None,
                          help="if set, ignores --num-train and runs a "
                                   "curriculum preset")
    p.add_argument("--level", type=int, default=None,
                          help="run only this level (combine with --num + "
                                   "--split for shell-driver dispatch)")
    p.add_argument("--num", type=int, default=None,
                          help="instances when --level is set")
    p.add_argument("--split", default="train",
                          help="which split to write into when --level is set")
    p.add_argument("--config-offset", type=int, default=0,
                          help="starting config number (for shell-driver "
                                   "dispatch across processes)")
    p.add_argument("--no-domain-copy", action="store_true",
                          help="don't copy domain.pddl to output_dir")
    p.add_argument("--bundle-v2", action="store_true",
                          help="generate the v2 4-dataset bundle "
                                   "(train+val Option-B, eval_pre_b, "
                                   "eval_full).  Output dirs are flat "
                                   "(no L<level>/ subdirs).")
    p.add_argument("--bundle-v4", action="store_true",
                          help="generate the v4 4-dataset bundle "
                                   "(train_600 + val_100 with dense_front_n "
                                   "L4 n∈[10,14] + 50%% return at L3/L4; "
                                   "eval_pre_b + eval_full unchanged). "
                                   "Output dirs are flat.")
    p.add_argument("--bundle-v4-5", action="store_true",
                          help="generate the v4.5 access-19-focused "
                                   "bundle (train_600 + val_10, all "
                                   "dense_front_n with n∈[3,18] uniform "
                                   "and 100%% return; val biases half to "
                                   "canonical_18). Output dirs flat.")
    p.add_argument("--verbose", action="store_true")
    args = p.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    if not args.no_domain_copy:
        _copy_domain(args.output_dir)

    # Per-level shell-driver mode.
    if args.level is not None:
        if args.num is None:
            print("--level requires --num", flush=True)
            return 2
        level_subdir = f"L{args.level}"
        stats = _generate_split_parallel(
            args.split, args.num, args, args.output_dir, args.seed,
            level=args.level, level_subdir=level_subdir,
            config_offset=args.config_offset,
        )
        _print_stats(f"{args.split}/L{args.level}", stats, 0.0)
        return 0

    # Curriculum-spec mode.
    if args.curriculum_spec is not None:
        spec = _CURRICULA[args.curriculum_spec]
        _run_curriculum("train", spec, args, args.output_dir, args.seed,
                                curriculum_spec=args.curriculum_spec)
        if args.num_val > 0:
            _run_curriculum("val", _CURRICULA["val_per_level"],
                                  args, args.output_dir, args.seed + 100)
        if args.num_test > 0:
            _run_curriculum("test", _CURRICULA["test_per_level"],
                                  args, args.output_dir, args.seed + 200)
        return 0

    # V4.5 bundle mode — access-19-focused full training set.  No
    # curriculum tiers; every problem is dense_front_n(n ∈ [3, 18])
    # with 100% return.  Val biases half to canonical_18.
    if args.bundle_v4_5:
        _run_curriculum("train", _CURRICULA["train_600_v4_5"],
                                args, args.output_dir, args.seed,
                                flat=True,
                                curriculum_spec="train_600_v4_5")
        _run_curriculum("val", _CURRICULA["val_10_v4_5"],
                                args, args.output_dir, args.seed + 100,
                                flat=True,
                                curriculum_spec="val_10_v4_5")
        return 0

    # V4 bundle mode — train_600 + val_100 with dense_front_n L4 +
    # 50% return at L3/L4; eval splits unchanged.
    if args.bundle_v4:
        _run_curriculum("train", _CURRICULA["train_600_v4"],
                                args, args.output_dir, args.seed,
                                flat=True,
                                curriculum_spec="train_600_v4")
        _run_curriculum("val", _CURRICULA["val_100_v4"],
                                args, args.output_dir, args.seed + 100,
                                flat=True,
                                curriculum_spec="val_100_v4")
        _run_curriculum("eval_pre_b", _CURRICULA["eval_30_pre_b"],
                                args, args.output_dir, args.seed + 200,
                                flat=True,
                                curriculum_spec="eval_30_pre_b")
        _run_curriculum("eval_full", _CURRICULA["eval_30_full_a19"],
                                args, args.output_dir, args.seed + 300,
                                flat=True,
                                curriculum_spec="eval_30_full_a19")
        return 0

    # V2 bundle mode — 4 datasets in one shot, flat output dirs.
    if args.bundle_v2:
        # train + val: Option-B distribution (L4 = canonical_12).
        _run_curriculum("train", _CURRICULA["train_300_option_b"],
                                args, args.output_dir, args.seed,
                                flat=True,
                                curriculum_spec="train_300_option_b")
        _run_curriculum("val", _CURRICULA["val_50_option_b"],
                                args, args.output_dir, args.seed + 100,
                                flat=True,
                                curriculum_spec="val_50_option_b")
        # eval_pre_b: original curriculum with canonical_18 at L4.
        _run_curriculum("eval_pre_b", _CURRICULA["eval_30_pre_b"],
                                args, args.output_dir, args.seed + 200,
                                flat=True,
                                curriculum_spec="eval_30_pre_b")
        # eval_full: 30 canonical_18 + return-all (L4 only).
        _run_curriculum("eval_full", _CURRICULA["eval_30_full_a19"],
                                args, args.output_dir, args.seed + 300,
                                flat=True,
                                curriculum_spec="eval_30_full_a19")
        return 0

    print("Specify --curriculum-spec, --bundle-v2, or (--level + --num).",
              flush=True)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
