"""Regenerate an access-19 dataset under the combined pick-place
action set (``domain_combined.pddl``).

Reads an existing access-19 dataset directory (e.g. ``access19_v4``)
and writes a new directory (``access19_v4_combined``) where:

  * every ``problem.pddl`` is the same init + goal as the source,
    only the ``(:domain …)`` reference is updated to
    ``tabletop-access-combined``
  * every ``problem.pddl.plan`` has each consecutive ``(pick X cf)``
    + ``(put X ct)`` pair collapsed into a single
    ``(pick-place X cf ct)`` action

No re-planning, no MuJoCo, no IK.  Just text transformation — runs
in seconds on a single CPU even for the full v4 dataset.

Why this is correct
-------------------

The phased / astar planners that built the v4 plans interleave pick
and put for the SAME object adjacent in the plan: every pick is
immediately followed by the put of the same object.  This is the
standard pick-and-place pattern under symbolic constraints that the
access-19 chains enforce (gripper opens between actions, no
"transport with held block" actions).

The combined ``pick-place`` action has identical pre/effect to a
``pick`` + ``put`` of the same object: ``(occupied cf X) ∧
(empty ct) → (occupied ct X) ∧ (empty cf)``.  So collapsing pairs is
a sound transformation.

Usage::

    python -m tampanda.symbolic.domains.access19.regenerate_combined \\
        --input-dir data/access19_v4 \\
        --output-dir data/access19_v4_combined
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
import time
from pathlib import Path
from typing import List, Tuple


_HERE = Path(__file__).parent
_DOMAIN_COMBINED = (_HERE / "pddl" / "domain_combined.pddl").resolve()


def collapse_pick_put_pairs(plan: List[Tuple]) -> List[Tuple]:
    """Collapse consecutive ``(pick X cf)(put X ct)`` pairs into
    ``(pick-place X cf ct)``.

    Pass-through for actions that don't form a same-object pair
    (defensive — shouldn't happen on valid access-19 plans).
    """
    out: List[Tuple] = []
    i = 0
    while i < len(plan):
        action = plan[i]
        verb = action[0]
        if verb == "pick" and i + 1 < len(plan):
            nxt = plan[i + 1]
            if (nxt[0] == "put" and len(action) >= 3 and len(nxt) >= 3
                    and action[1] == nxt[1]):
                obj = action[1]
                cf = action[2]
                ct = nxt[2]
                out.append(("pick-place", obj, cf, ct))
                i += 2
                continue
        out.append(action)
        i += 1
    return out


def _parse_plan_file(plan_path: Path) -> Tuple[List[Tuple], List[str]]:
    """Return ``(actions, trailing_comments)``.  The first ``; cost =
    …`` line is regenerated by the caller; other comments preserved.
    """
    actions: List[Tuple] = []
    comments: List[str] = []
    text = plan_path.read_text()
    for line in text.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith(";"):
            comments.append(s)
            continue
        m = re.match(r"\((\S+)\s+(.+)\)\s*$", s)
        if m:
            actions.append((m.group(1), *m.group(2).split()))
    return actions, comments


def _write_plan_file(
    plan_path: Path, actions: List[Tuple], comments: List[str]
) -> None:
    lines: List[str] = []
    for a in actions:
        lines.append("(" + " ".join(str(x) for x in a) + ")")
    lines.append(f"; cost = {len(actions)} (unit cost)")
    # Preserve original comments except the original cost line.
    for c in comments:
        if c.startswith("; cost ="):
            continue
        lines.append(c)
    lines.append("; combined: pick/put pairs collapsed to pick-place")
    plan_path.write_text("\n".join(lines) + "\n")


def _transform_problem_file(src: Path, dst: Path) -> None:
    text = src.read_text()
    text = text.replace(
        "(:domain tabletop-access)",
        "(:domain tabletop-access-combined)",
    )
    dst.write_text(text)


def _regenerate_split(
    in_split: Path, out_split: Path,
) -> Tuple[int, int]:
    """Returns ``(n_problems, n_plans)`` written."""
    out_split.mkdir(parents=True, exist_ok=True)
    n_problems = 0
    n_plans = 0
    for prob_path in sorted(in_split.glob("config_*.pddl")):
        if prob_path.suffix != ".pddl":
            continue
        _transform_problem_file(prob_path, out_split / prob_path.name)
        n_problems += 1
        plan_path = prob_path.with_suffix(".pddl.plan")
        if not plan_path.exists():
            continue
        actions, comments = _parse_plan_file(plan_path)
        collapsed = collapse_pick_put_pairs(actions)
        _write_plan_file(out_split / plan_path.name, collapsed, comments)
        n_plans += 1
    return n_problems, n_plans


def regenerate(input_dir: Path, output_dir: Path) -> int:
    """Main entry: copy + transform a dataset directory.  Returns
    total problem count across all splits.
    """
    if not input_dir.exists():
        print(f"FAIL: input dir does not exist: {input_dir}",
              file=sys.stderr)
        return 0
    output_dir.mkdir(parents=True, exist_ok=True)

    # Bundle the combined domain as ``domain.pddl`` so existing tools
    # that look for ``domain.pddl`` in the dataset root work
    # unchanged.  No separate planner / rgnet split because no PDDL
    # planner will plan from this domain — plans are derived from
    # the source dataset.
    if _DOMAIN_COMBINED.exists():
        shutil.copy(_DOMAIN_COMBINED, output_dir / "domain.pddl")
    else:
        print(f"WARN: domain_combined.pddl not found at {_DOMAIN_COMBINED}",
              file=sys.stderr)

    total_problems = 0
    summary_lines: List[str] = []
    splits = ("train", "val", "eval_pre_b", "eval_full")
    for split in splits:
        in_split = input_dir / split
        if not in_split.exists():
            continue
        out_split = output_dir / split
        t0 = time.perf_counter()
        np, nplans = _regenerate_split(in_split, out_split)
        dt = time.perf_counter() - t0
        total_problems += np
        summary_lines.append(
            f"  {split:<12} {np:>4} problems · {nplans:>4} plans · "
            f"{dt:.1f}s"
        )

    print(f"\n=== regenerated combined dataset at {output_dir} ===")
    print("\n".join(summary_lines))
    print(f"  total: {total_problems} problems")
    return total_problems


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--input-dir", type=Path, required=True,
                          help="source access-19 dataset (e.g. "
                                   "data/access19_v4)")
    p.add_argument("--output-dir", type=Path, required=True,
                          help="destination (e.g. "
                                   "data/access19_v4_combined)")
    args = p.parse_args()
    n = regenerate(args.input_dir, args.output_dir)
    return 0 if n > 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
