"""Multilevel-blocks dataset generation — PDDL problems with feasibility
validation.

For each generated instance:

1. A buildable structure template is sampled (cube_tower /
   oblong_tower / upright_bridges / long_pyramid).
2. The initial state (all source blocks on the parts table) and the
   goal state (target structure on the stack table) are derived from
   the template.
3. A plan is generated by reverse construction: for each block in
   dependency-respecting build order, the script emits
   ``pick → [in-hand transforms] → put`` actions.
4. Every action is validated via :func:`check_action_sequence` with
   the FAST executor.  Instances whose plan fails partway are
   rejected (the failed action's error is logged for debugging).
5. PDDL problem + plan + visualisation are saved.

Output layout mirrors rgnet's ``data/pddl_domains/example/blocks/``::

    data/multilevel_blocks/
    ├── domain.pddl
    ├── train/
    │   ├── config_1.pddl
    │   ├── config_1.pddl.plan
    │   ├── viz/
    │   │   └── config_1.png
    │   └── ...
    ├── test/
    └── val/

Usage::

    python -m tampanda.symbolic.domains.multilevel_blocks.generate_data
    python -m tampanda.symbolic.domains.multilevel_blocks.generate_data \\
        --num-train 200 --num-test 20 --num-val 20 \\
        --templates cube_tower oblong_tower upright_bridges long_pyramid \\
        --num-workers 4

CLI flags mirror tabletop/generate_data.py.
"""
from __future__ import annotations

import argparse
import multiprocessing as mp
import shutil
import tempfile
import time
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

try:
    import mujoco
except ImportError:
    mujoco = None  # type: ignore

from tampanda.symbolic.domains.multilevel_blocks import (
    MultilevelBlocksConfig,
    cube_block_name,
    long_block_name,
    make_multilevel_blocks_builder,
    make_multilevel_blocks_bridge,
    oblong_block_name,
    restore_state,
    stack_region_name,
)
from tampanda.symbolic.domains.multilevel_blocks.feasibility import (
    _make_executor,
    check_action_sequence,
)
from tampanda.symbolic.domains.multilevel_blocks.templates import (
    Template,
    compound,
    cube_pick_put,
    cube_tower,
    double_bridges,
    long_pyramid,
    multi_tower,
    oblong_tower,
    random_mix,
    simple_long_rotate,
    simple_long_rotate_y_to_x,
    simple_long_x,
    simple_long_y,
    simple_make_long_upright_from_x,
    simple_make_long_upright_from_y,
    simple_make_upright_from_y,
    simple_oblong_flat_x,
    simple_oblong_flat_y,
    simple_oblong_rotate_y_to_x,
    simple_pick_long_upright_then_put_long_upright,
    simple_pick_upright_then_put_upright,
    simple_unstack_long_to_flat_x,
    simple_unstack_long_to_flat_y,
    simple_unstack_oblong_to_flat_x,
    simple_unstack_oblong_to_flat_y,
    simple_upright_pickput,
    staircase,
    tower_on_bridge,
    upright_bridges,
)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_HERE = Path(__file__).parent
_DOMAIN = (_HERE / "pddl" / "domain.pddl").resolve()
# Bundled into each generated dataset.  The derived-predicate variant
# replaces the inline disjunctive (exists ...) preconditions with a
# (:derived (supported ?c)) predicate — needed by pymimir-based GNN
# encoders (rgnet) which split disjunctive action preconditions into
# multiple schemas with witness parameters of varying arity.  tampanda's
# own runtime keeps using ``domain.pddl`` because unified-planning
# 1.2.0's PDDLReader doesn't accept the :derived-predicates requirement.
_DOMAIN_BUNDLED = (_HERE / "pddl" / "domain_derived.pddl").resolve()

_DEFAULT_OUTPUT_DIR = Path("data/multilevel_blocks")
_DEFAULT_TRAIN = 200
_DEFAULT_TEST = 20
_DEFAULT_VAL = 20
_DEFAULT_NUM_WORKERS = 1
_DEFAULT_SEED = 42

_TEMPLATE_NAMES = (
    "cube_pick_put",       # L0
    "simple_long_x",       # L0 — primitive: put-long-x
    "simple_oblong_flat_x",   # L0 — primitive: put-flat-x
    "simple_oblong_flat_y",   # L0 — primitive: pick-flat-y + put-flat-y
    "simple_long_y",          # L0 — primitive: pick-long-y
    "simple_pick_upright_then_put_upright",   # L0 — primitive: pick-upright
    "simple_pick_long_upright_then_put_long_upright",  # L0 — primitive: pick-long-upright + put-long-upright
    "simple_upright_pickput",  # L1 — primitive: put-upright + make-upright-from-x
    "simple_long_rotate",  # L1 — primitive: put-long-y + turn-long-x-to-y
    "simple_oblong_rotate_y_to_x",  # L1 — primitive: turn-y-to-x
    "simple_long_rotate_y_to_x",    # L1 — primitive: turn-long-y-to-x
    "simple_make_upright_from_y",   # L1 — primitive: make-upright-from-y
    "simple_make_long_upright_from_x",  # L1 — primitive: make-long-upright-from-x
    "simple_make_long_upright_from_y",  # L1 — primitive: make-long-upright-from-y
    "cube_tower",          # L1
    "oblong_tower",        # L2 (same-orient) / L3 (orient-change)
    "long_pyramid",        # L2
    "simple_unstack_oblong_to_flat_x",  # L2 — primitive: make-flat-x-from-upright
    "simple_unstack_oblong_to_flat_y",  # L2 — primitive: make-flat-y-from-upright
    "simple_unstack_long_to_flat_x",    # L2 — primitive: make-long-flat-x-from-upright
    "simple_unstack_long_to_flat_y",    # L2 — primitive: make-long-flat-y-from-upright
    "upright_bridges",     # L4
    "tower_on_bridge",     # L4
    "multi_tower",         # L5
    "double_bridges",      # L5
    "staircase",           # L5
    "compound",            # L5
    "random_mix",          # any-difficulty fallback
)

# Map each difficulty level to its template options.  Used by
# --curriculum-spec to filter templates per level.
_LEVELS: Dict[int, List[str]] = {
    # L0 / L1 / L2 carry primitive-exposure templates that exercise EVERY
    # action in the multilevel_blocks domain at least once in a 2-3 action
    # single-block problem.  Coverage breakdown:
    #   L0 — pick/put with no in-hand transform (7 templates)
    #   L1 — pick + in-hand transform + put (8 templates incl. cube_tower)
    #   L2 — pick-from-stack + in-hand transform + put-flat (6 templates
    #        incl. existing oblong_tower / long_pyramid)
    # See templates.py for which action each new template covers.
    0: ["cube_pick_put", "simple_long_x",
         "simple_oblong_flat_x", "simple_oblong_flat_y",
         "simple_long_y",
         "simple_pick_upright_then_put_upright",
         "simple_pick_long_upright_then_put_long_upright"],
    1: ["cube_tower",
         "simple_upright_pickput", "simple_long_rotate",
         "simple_oblong_rotate_y_to_x", "simple_long_rotate_y_to_x",
         "simple_make_upright_from_y",
         "simple_make_long_upright_from_x",
         "simple_make_long_upright_from_y"],
    2: ["oblong_tower", "long_pyramid",
         "simple_unstack_oblong_to_flat_x",
         "simple_unstack_oblong_to_flat_y",
         "simple_unstack_long_to_flat_x",
         "simple_unstack_long_to_flat_y"],
    3: ["oblong_tower", "cube_tower"],                  # h=4, orient-change
    4: ["upright_bridges", "tower_on_bridge"],          # FULL executor only
    5: ["multi_tower", "staircase", "compound", "double_bridges"],
}

# Historically L4 used the FULL executor because the FastFeasibilityExecutor
# had IK basin issues in put_upright's column-align / descent.  After the
# Phase 3.7 LUT-seeded executor (de4cf03) + casing fixes (330c88c, d07d72a)
# + Phase 3.8 cached probe goal_q reuse on descent, the fast executor
# handles put_upright reliably (verified 40/40 L4 val plans pass under
# fast).  L4 now uses fast mode like all other levels — also avoids the
# per_action_restore + full-executor interaction that left the held
# block at a slightly different pose between actions, blocking
# downstream put-* steps in datagen.
_FULL_EXECUTOR_LEVELS: set = set()

# Curriculum-spec presets.  Each preset is a list of (level, count) tuples.
# train_600 distribution: 60, 120, 120, 120, 90, 90 = 600.
_CURRICULA: Dict[str, List[Tuple[int, int]]] = {
    "train_600": [(0, 60), (1, 120), (2, 120), (3, 120), (4, 90), (5, 90)],
    "train_400": [(0, 40), (1, 80), (2, 80), (3, 80), (4, 60), (5, 60)],
    "train_200": [(0, 20), (1, 40), (2, 40), (3, 40), (4, 30), (5, 30)],
    # train_l0_l4: L5 held out for OOD evaluation.  L0/L1 counts bumped
    # (140/160) to accommodate the expanded primitive-exposure template
    # set — each new template gets ~20 problems, similar to the legacy
    # cube_pick_put / cube_tower counts.
    "train_l0_l4": [(0, 140), (1, 160), (2, 120), (3, 120), (4, 90)],
    "val_per_level": [(k, 20) for k in range(6)],
    "test_per_level": [(k, 20) for k in range(6)],
}


# ---------------------------------------------------------------------------
# Action builders
# ---------------------------------------------------------------------------


def _sort_cells_for_orientation(cells: List[str], orientation: str
                                   ) -> List[str]:
    """Sort cell IDs into the canonical order each PDDL action expects.

    * flat-x / long-x: ascending ix.
    * flat-y / long-y: ascending iy.
    * upright (oblong 2-cell) / long-upright (3-cell): ascending region
      (so L0 < L1 < L2).
    """
    from tampanda.symbolic.workspace import Cell
    parsed = [Cell.parse(c) for c in cells]
    if orientation in ("flat-x", "long-x"):
        parsed.sort(key=lambda c: c.ix)
    elif orientation in ("flat-y", "long-y"):
        parsed.sort(key=lambda c: c.iy)
    elif orientation in ("upright", "upright-2", "long-upright"):
        parsed.sort(key=lambda c: c.region)
    return [c.id for c in parsed]


def _action_for_pick(shape: str, orientation: str,
                          block: str, cells: List[str]) -> Tuple:
    """Build the PDDL pick action tuple for (shape, orientation, cells)."""
    sorted_cells = _sort_cells_for_orientation(cells, orientation)
    if shape == "cube":
        if len(sorted_cells) != 1:
            raise ValueError("cube must have 1 cell")
        return ("pick-cube", block, sorted_cells[0])
    if shape == "oblong":
        if orientation == "flat-x":
            return ("pick-flat-x", block, sorted_cells[0], sorted_cells[1])
        if orientation == "flat-y":
            return ("pick-flat-y", block, sorted_cells[0], sorted_cells[1])
        if orientation == "upright":
            return ("pick-upright", block, sorted_cells[0], sorted_cells[1])
    if shape == "long":
        if orientation == "flat-x":
            return ("pick-long-x", block, *sorted_cells)
        if orientation == "flat-y":
            return ("pick-long-y", block, *sorted_cells)
        if orientation == "upright":
            return ("pick-long-upright", block, *sorted_cells)
    raise ValueError(f"unsupported (shape, orientation): {shape, orientation}")


def _action_for_put(shape: str, orientation: str,
                         block: str, cells: List[str]) -> Tuple:
    """Build the PDDL put action tuple — same signature as pick.

    Note: put-cube/flat-*/upright follow the same naming pattern as
    pick-*, just with ``put-`` prefix.
    """
    sorted_cells = _sort_cells_for_orientation(cells, orientation)
    if shape == "cube":
        return ("put-cube", block, sorted_cells[0])
    if shape == "oblong":
        if orientation == "flat-x":
            return ("put-flat-x", block, sorted_cells[0], sorted_cells[1])
        if orientation == "flat-y":
            return ("put-flat-y", block, sorted_cells[0], sorted_cells[1])
        if orientation == "upright":
            return ("put-upright", block, sorted_cells[0], sorted_cells[1])
    if shape == "long":
        if orientation == "flat-x":
            return ("put-long-x", block, *sorted_cells)
        if orientation == "flat-y":
            return ("put-long-y", block, *sorted_cells)
        if orientation == "upright":
            return ("put-long-upright", block, *sorted_cells)
    raise ValueError(f"unsupported (shape, orientation): {shape, orientation}")


def _transform_actions(shape: str, src_orient: str, dst_orient: str,
                            block: str) -> List[Tuple]:
    """Emit the chain of in-hand transform actions to go from src to dst."""
    if src_orient == dst_orient:
        return []
    if shape == "cube":
        if src_orient != dst_orient:
            raise ValueError("cubes have no orientations")
        return []
    long_prefix = "-long" if shape == "long" else ""
    # Two-step transforms (e.g., upright → flat-x → flat-y) might be
    # needed; we shortcut via the direct PDDL action where possible.
    direct = {
        ("flat-x", "flat-y"): f"turn{long_prefix}-x-to-y",
        ("flat-y", "flat-x"): f"turn{long_prefix}-y-to-x",
        ("flat-x", "upright"): f"make{long_prefix}-upright-from-x",
        ("flat-y", "upright"): f"make{long_prefix}-upright-from-y",
        ("upright", "flat-x"): f"make{long_prefix}-flat-x-from-upright",
        ("upright", "flat-y"): f"make{long_prefix}-flat-y-from-upright",
    }
    key = (src_orient, dst_orient)
    if key in direct:
        return [(direct[key], block)]
    raise ValueError(
        f"no direct transform from {src_orient!r} to {dst_orient!r}; "
        "two-step transforms not yet implemented"
    )


def _block_shape(block_name: str) -> str:
    if block_name.startswith("cube_"):
        return "cube"
    if block_name.startswith("oblong_"):
        return "oblong"
    if block_name.startswith("long_"):
        return "long"
    raise ValueError(f"unknown block name: {block_name}")


def build_plan(template: Template) -> List[Tuple]:
    """Generate the action sequence that builds ``template``.

    Walks ``template.build_order`` and, for each block, emits:
      pick(source) → [transforms] → put(target)
    """
    src_by_block = {b: (cells, orient)
                       for b, cells, orient in template.source_placements}
    goal_by_block = {b: (cells, orient)
                          for b, cells, orient in template.goal_placements}

    plan: List[Tuple] = []
    for block in template.build_order:
        s_cells, s_orient = src_by_block[block]
        g_cells, g_orient = goal_by_block[block]
        shape = _block_shape(block)
        plan.append(_action_for_pick(shape, s_orient, block, s_cells))
        plan.extend(_transform_actions(shape, s_orient, g_orient, block))
        plan.append(_action_for_put(shape, g_orient, block, g_cells))
    return plan


# ---------------------------------------------------------------------------
# PDDL writer
# ---------------------------------------------------------------------------


def _compute_problem_cells(template, workspace,
                                 ) -> "frozenset[str]":
    """Return the minimal cell set needed to express the template's plan.

    Strategy:

    * Include every cell named in ``source_placements`` or
      ``goal_placements``.
    * For every stack cell included so far, include all cells directly
      below it in the same column down to L0 (needed so the ``above``
      predicate's support chain resolves correctly during put-* support
      checks, and so the planner / GNN can see the column structure).
    * For every cell included so far, include its east / north / above
      neighbours when they exist in the workspace (one-cell adjacency
      buffer so adjacency-conditioned puts can be GNN-grounded against
      reasonable alternatives, not the bare minimum).

    Adjacency predicates (east-of / north-of / above) are emitted ONLY
    between cells that are both in this returned set.  Same for the
    ``puttable`` predicate.
    """
    from tampanda.symbolic.workspace import Cell
    from tampanda.symbolic.domains.multilevel_blocks.bridge import (
        _cell_east, _cell_north, _cells_above,
    )

    used: set = set()
    for _block, cell_ids, _orient in template.source_placements:
        used.update(cell_ids)
    for _block, cell_ids, _orient in template.goal_placements:
        used.update(cell_ids)

    # Support chain: for any stack cell, include every cell directly
    # below it in the same column down to L0.
    support: set = set()
    for c_id in used:
        if not c_id.startswith("stack_L"):
            continue
        c = Cell.parse(c_id)
        level = int(c.region.split("_L")[1])
        for k in range(level):
            support.add(f"stack_L{k}__{c.ix}_{c.iy}")
    used.update(support)

    # Cache the workspace's full cell-id set once for cheap membership.
    workspace_cells = {
        cell.id
        for r in workspace.regions
        for cell in workspace[r].cells()
    }

    # 1-cell adjacency buffer (east, north, above) so action grounding has
    # a few neighbours to consider, not just the cells the plan touches.
    buffer: set = set()
    for c_id in list(used):
        c = Cell.parse(c_id)
        for neigh in (_cell_east(c, workspace),
                            _cell_north(c, workspace),
                            _cells_above(c, workspace)):
            if neigh is not None and neigh.id in workspace_cells:
                buffer.add(neigh.id)
    used.update(buffer)

    return frozenset(used)


def _enumerate_static_init(workspace, cfg: MultilevelBlocksConfig,
                                  *,
                                  cells_subset: "Optional[frozenset[str]]" = None,
                                  ) -> Tuple[List[str], List[str]]:
    """Return (object_names, static_init_predicates) for a PDDL problem.

    Static predicates: cube/oblong/long b, in-parts c, in-stack c,
    puttable c (stack cells only), east-of c1 c2, north-of c1 c2,
    above c-low c-up.

    Args:
        workspace: the multilevel_blocks Workspace.
        cfg: domain config.
        cells_subset: if provided, restrict declared cells to this set
            (per-problem dynamic grid).  If None, declare every cell in
            the workspace (back-compat path).
    """
    from tampanda.symbolic.workspace import Cell
    from tampanda.symbolic.domains.multilevel_blocks.bridge import (
        _cell_east, _cell_north, _cells_above,
    )

    cells: List[str] = []
    blocks: List[str] = []
    init: List[str] = []

    # Cells (filtered by subset if given)
    for region_name in workspace.regions:
        region = workspace[region_name]
        for cell in region.cells():
            if cells_subset is None or cell.id in cells_subset:
                cells.append(cell.id)
    cell_set = set(cells)

    # Blocks (alphabetical, names-only)
    for i in range(cfg.n_cubes):
        blocks.append(cube_block_name(i))
    for i in range(cfg.n_oblong):
        blocks.append(oblong_block_name(i))
    for i in range(cfg.n_long):
        blocks.append(long_block_name(i))

    # Static shape predicates
    for i in range(cfg.n_cubes):
        init.append(f"(cube {cube_block_name(i)})")
    for i in range(cfg.n_oblong):
        init.append(f"(oblong {oblong_block_name(i)})")
    for i in range(cfg.n_long):
        init.append(f"(long {long_block_name(i)})")

    # in-parts / in-stack + puttable (stack only)
    for c in cells:
        if c.startswith("parts__"):
            init.append(f"(in-parts {c})")
        elif c.startswith("stack_L"):
            init.append(f"(in-stack {c})")
            init.append(f"(puttable {c})")

    # Adjacency: east-of, north-of, above — only when BOTH cells are
    # in the declared subset.
    for c_id in cells:
        c = Cell.parse(c_id)
        east = _cell_east(c, workspace)
        if east is not None and east.id in cell_set:
            init.append(f"(east-of {c.id} {east.id})")
        north = _cell_north(c, workspace)
        if north is not None and north.id in cell_set:
            init.append(f"(north-of {c.id} {north.id})")
        up = _cells_above(c, workspace)
        if up is not None and up.id in cell_set:
            init.append(f"(above {c.id} {up.id})")

    return blocks + cells, init


def write_pddl_problem(
    template: Template,
    workspace,
    cfg: MultilevelBlocksConfig,
    output_path: Path,
    problem_name: str,
) -> None:
    """Write a complete PDDL problem file matching the multilevel_blocks
    domain.

    Includes all static predicates (shape, region, adjacency), dynamic
    initial-state predicates (in-block-at-cell, empty, gripper-empty),
    and a goal conjunction over the template's goal_placements.

    The declared cell set is restricted per-problem to only the cells
    the plan touches (plus 1-cell adjacency + support chain) via
    ``_compute_problem_cells`` — this is what shrinks the GNN object
    list from ~763 down to ~50-100 per problem.
    """
    cells_subset = _compute_problem_cells(template, workspace)
    objects, statics = _enumerate_static_init(
        workspace, cfg, cells_subset=cells_subset,
    )

    # Split objects by type for the :objects section.
    blocks = [o for o in objects
                  if o.startswith(("cube_", "oblong_", "long_"))]
    cells_objs = [o for o in objects
                       if o.startswith(("parts__", "stack_L"))]

    # Dynamic init: place each block at its source cells.
    src_dyn: List[str] = []
    occupied_cells: set = set()
    for block, cell_ids, _orient in template.source_placements:
        for cid in cell_ids:
            src_dyn.append(f"(in {block} {cid})")
            occupied_cells.add(cid)

    # Empty cells: everything except occupied.
    for c in cells_objs:
        if c not in occupied_cells:
            src_dyn.append(f"(empty {c})")

    # Gripper starts empty.
    src_dyn.append("(gripper-empty)")

    # Goal: conjunction of (in block cell) for every (block, cell) in
    # goal_placements.
    goal_atoms: List[str] = []
    for block, cell_ids, _orient in template.goal_placements:
        for cid in cell_ids:
            goal_atoms.append(f"(in {block} {cid})")

    # Format
    lines: List[str] = []
    lines.append(f"(define (problem {problem_name})")
    lines.append("  (:domain multilevel-blocks)")
    lines.append("  (:objects")
    if blocks:
        lines.append(f"    {' '.join(blocks)} - block")
    lines.append(f"    {' '.join(cells_objs)} - cell")
    lines.append("  )")
    lines.append("  (:init")
    for p in statics:
        lines.append(f"    {p}")
    for p in src_dyn:
        lines.append(f"    {p}")
    lines.append("  )")
    lines.append("  (:goal (and")
    for a in goal_atoms:
        lines.append(f"    {a}")
    lines.append("  ))")
    lines.append(")")
    output_path.write_text("\n".join(lines) + "\n")


def write_plan_file(
    plan: List[Tuple],
    output_path: Path,
    metadata: Dict[str, Any],
) -> None:
    """Write a .pddl.plan file with one action per line + metadata trailer."""
    lines = []
    for action in plan:
        lines.append("(" + " ".join(str(a) for a in action) + ")")
    lines.append(f"; cost = {len(plan)} (unit cost)")
    for k, v in metadata.items():
        lines.append(f"; {k}: {v}")
    output_path.write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Visualization
# ---------------------------------------------------------------------------


def _setup_camera(cfg: MultilevelBlocksConfig, kind: str = "stack"
                    ) -> "mujoco.MjvCamera":
    """Camera presets.

    ``stack`` — close, looking at the stack table from the robot's
    front-right, top-down angle.  Used for goal snapshots.

    ``parts`` — close, looking at the parts table from behind the
    robot.  Used for initial-kit snapshots.  Same elevation as stack
    so the two side-by-side renders look symmetric.
    """
    cam = mujoco.MjvCamera()
    sp = cfg.stack_table_pos
    pp = cfg.parts_table_pos
    if kind == "stack":
        cam.azimuth = 180   # look from -y toward stack table at +y
        cam.elevation = -35
        cam.distance = 0.8
        cam.lookat[:] = [sp[0], sp[1], sp[2] + 0.18]
    else:   # parts
        cam.azimuth = 0     # look from +y toward parts table at -y
        cam.elevation = -35
        cam.distance = 0.8
        cam.lookat[:] = [pp[0], pp[1], pp[2] + 0.05]
    return cam


def render_template_pair(
    template: Template,
    workspace,
    cfg: MultilevelBlocksConfig,
    env,
    output_path: Path,
) -> None:
    """Render side-by-side PNG: initial state (on parts) + goal (on stack).

    Two snapshots concatenated horizontally.  Uses a wide camera that
    captures both tables.
    """
    if mujoco is None:
        return

    env.model.vis.global_.offwidth = max(1280, env.model.vis.global_.offwidth)
    env.model.vis.global_.offheight = max(720, env.model.vis.global_.offheight)
    renderer = mujoco.Renderer(env.model, height=720, width=640)
    cam_parts = _setup_camera(cfg, kind="parts")
    cam_stack = _setup_camera(cfg, kind="stack")

    # Initial state: all blocks at source cells.  Use the parts camera
    # so the kit is visible up close.
    init_state = _state_from_placements(template.source_placements)
    restore_state(env, workspace, cfg, init_state)
    renderer.update_scene(env.data, camera=cam_parts)
    img_init = renderer.render()

    # Final state: all blocks at goal cells.  Use the stack camera.
    goal_state = _state_from_placements(template.goal_placements)
    restore_state(env, workspace, cfg, goal_state)
    renderer.update_scene(env.data, camera=cam_stack)
    img_goal = renderer.render()

    # Concatenate horizontally with a thin separator.
    sep = np.full((img_init.shape[0], 8, 3), 32, dtype=img_init.dtype)
    img = np.concatenate([img_init, sep, img_goal], axis=1)

    try:
        import cv2  # type: ignore
        cv2.imwrite(str(output_path), img[:, :, ::-1])
    except ImportError:
        try:
            import matplotlib.pyplot as plt  # type: ignore
            plt.imsave(str(output_path), img)
        except ImportError:
            pass
    finally:
        renderer.close()


def _state_from_placements(
    placements: List[Tuple[str, List[str], str]],
) -> Dict[Tuple, bool]:
    """Build a minimal state dict containing just the (in ...) predicates."""
    state: Dict[Tuple, bool] = {}
    for block, cells, _ in placements:
        for c in cells:
            state[("in", block, c)] = True
    return state


# ---------------------------------------------------------------------------
# Generation loop
# ---------------------------------------------------------------------------


def _safe_iy(rng: np.random.Generator, cfg: MultilevelBlocksConfig,
                 *, max_iy_cap: int = 3) -> int:
    """Sample iy biased toward small values (front of stack table).

    put_upright has IK reach limits at high iy on the default stack
    grid; templates with upright actions should clamp here.  For non-
    upright templates the cap is ignored.
    """
    cap = min(max_iy_cap, cfg.stack_grid_cells[1] - 4)
    return int(rng.integers(0, cap + 1))


def _maybe_disable_hand_capsule(env, args) -> None:
    """Disable the Franka hand_capsule bounding-capsule collision geom.

    The 4cm-radius × 6cm-half-length capsule is a conservative bounding
    approximation; its 10cm axial extent over-rejects feasible plans in
    dense structures (upright_bridges, tower_on_bridge), in particular
    failing the put_upright settle-to-traverse IK at z=0.50.  Real
    collisions are still checked via the hand_c mesh.
    """
    if getattr(args, "enable_hand_capsule", False):
        return
    for gid in range(env.model.ngeom):
        if env.model.geom(gid).name == "hand_capsule":
            env.model.geom_contype[gid] = 0
            env.model.geom_conaffinity[gid] = 0
            break


def _sample_template(
    rng: np.random.Generator,
    cfg: MultilevelBlocksConfig,
    allowed: Sequence[str],
    *,
    level: Optional[int] = None,
) -> Template:
    """Sample a template from ``allowed``.

    If ``level`` is given, the parameter ranges are biased to produce
    plans of the right difficulty (e.g., L1 only uses cube_tower with
    h=2..3; L3 forces orient-change in oblong_tower).
    """
    choice = str(rng.choice(allowed))
    cells_x, cells_y, cells_z = cfg.stack_grid_cells

    if choice == "cube_pick_put":
        ix = int(rng.integers(1, cells_x - 1))
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return cube_pick_put(ix, iy, cfg=cfg)

    if choice == "simple_long_x":
        # 3-cell long block along x — needs ix..ix+2 to fit.  Bias to
        # left-half (ix < 5) so put-long-x stays in the proven-feasible
        # range; right-half (ix >= 5) still allowed but biased low.
        if rng.random() < 0.85:
            ix = int(rng.integers(1, 4))   # ix ∈ {1, 2, 3}
        else:
            ix = int(rng.integers(4, cells_x - 3))
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return simple_long_x(ix, iy, cfg=cfg)

    if choice == "simple_upright_pickput":
        # Single upright oblong at (ix, iy) spanning L0+L1.  Bias toward
        # left-half ix where put-upright is reliable in fast mode.
        if rng.random() < 0.85:
            ix = int(rng.integers(1, 5))
        else:
            ix = int(rng.integers(5, cells_x - 1))
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return simple_upright_pickput(ix, iy, cfg=cfg)

    if choice == "simple_long_rotate":
        # Long block placed flat-y along (ix, iy..iy+2).  Bias toward
        # left-half ix and lower iy so the descent has room.
        if rng.random() < 0.85:
            ix = int(rng.integers(1, 5))
        else:
            ix = int(rng.integers(5, cells_x - 1))
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 4)
        return simple_long_rotate(ix, iy, cfg=cfg)

    # ---- Extended primitive-exposure templates ----
    # Helper to pick a left-biased ix (85 % left-half).
    def _biased_ix(low: int, high: int, mid: int = 5) -> int:
        if rng.random() < 0.85 and mid > low:
            return int(rng.integers(low, min(mid, high)))
        return int(rng.integers(low, high))

    if choice == "simple_oblong_flat_x":
        ix = _biased_ix(1, cells_x - 2)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return simple_oblong_flat_x(ix, iy, cfg=cfg)

    if choice == "simple_oblong_flat_y":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 3)
        return simple_oblong_flat_y(ix, iy, cfg=cfg)

    if choice == "simple_long_y":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 4)
        return simple_long_y(ix, iy, cfg=cfg)

    if choice == "simple_pick_upright_then_put_upright":
        # Source upright at (ix, iy), goal upright at different (ix2, iy2)
        # — both anchors left-biased; ensure they don't overlap.
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        ix2 = _biased_ix(1, cells_x - 1)
        iy2 = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        if (ix, iy) == (ix2, iy2):
            ix2 = (ix2 + 1) % (cells_x - 1) or 1
        return simple_pick_upright_then_put_upright(
            ix, iy, ix2, iy2, cfg=cfg,
        )

    if choice == "simple_pick_long_upright_then_put_long_upright":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        ix2 = _biased_ix(1, cells_x - 1)
        iy2 = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        if (ix, iy) == (ix2, iy2):
            ix2 = (ix2 + 1) % (cells_x - 1) or 1
        return simple_pick_long_upright_then_put_long_upright(
            ix, iy, ix2, iy2, cfg=cfg,
        )

    if choice == "simple_oblong_rotate_y_to_x":
        ix = _biased_ix(1, cells_x - 2)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return simple_oblong_rotate_y_to_x(ix, iy, cfg=cfg)

    if choice == "simple_long_rotate_y_to_x":
        ix = _biased_ix(1, cells_x - 3)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return simple_long_rotate_y_to_x(ix, iy, cfg=cfg)

    if choice == "simple_make_upright_from_y":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 3)
        return simple_make_upright_from_y(ix, iy, cfg=cfg)

    if choice == "simple_make_long_upright_from_x":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return simple_make_long_upright_from_x(ix, iy, cfg=cfg)

    if choice == "simple_make_long_upright_from_y":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 4)
        return simple_make_long_upright_from_y(ix, iy, cfg=cfg)

    if choice == "simple_unstack_oblong_to_flat_x":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        ix2 = _biased_ix(1, cells_x - 2)
        iy2 = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return simple_unstack_oblong_to_flat_x(
            ix, iy, ix2, iy2, cfg=cfg,
        )

    if choice == "simple_unstack_oblong_to_flat_y":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        ix2 = _biased_ix(1, cells_x - 1)
        iy2 = _safe_iy(rng, cfg, max_iy_cap=cells_y - 3)
        return simple_unstack_oblong_to_flat_y(
            ix, iy, ix2, iy2, cfg=cfg,
        )

    if choice == "simple_unstack_long_to_flat_x":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        ix2 = _biased_ix(1, cells_x - 3)
        iy2 = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return simple_unstack_long_to_flat_x(
            ix, iy, ix2, iy2, cfg=cfg,
        )

    if choice == "simple_unstack_long_to_flat_y":
        ix = _biased_ix(1, cells_x - 1)
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        ix2 = _biased_ix(1, cells_x - 1)
        iy2 = _safe_iy(rng, cfg, max_iy_cap=cells_y - 4)
        return simple_unstack_long_to_flat_y(
            ix, iy, ix2, iy2, cfg=cfg,
        )

    if choice == "cube_tower":
        if level is not None and level <= 1:
            h = int(rng.integers(2, min(cells_z, 3) + 1))
        elif level is not None and level == 3:
            h = int(rng.integers(4, min(cells_z, 4) + 1))  # tall only
        else:
            h = int(rng.integers(2, min(cells_z, 4) + 1))
        ix = int(rng.integers(1, cells_x - 1))
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return cube_tower(h, ix, iy, cfg=cfg)

    if choice == "oblong_tower":
        h = int(rng.integers(2, min(cells_z, 3) + 1))
        ix = int(rng.integers(1, cells_x - 3))
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        if level is not None and level == 3:
            # L3 must have orient change → flat target opposite of source.
            flat = "flat-y"   # source is always flat-x → triggers turn-x-to-y
        elif level is not None and level == 2:
            flat = "flat-x"   # same as source → no transform
        else:
            flat = str(rng.choice(["flat-x", "flat-y"]))
        return oblong_tower(h, ix, iy, cfg=cfg, flat_orientation=flat)

    if choice == "long_pyramid":
        ix = int(rng.integers(1, cells_x - 3))
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return long_pyramid(ix, iy, cfg=cfg)

    if choice == "upright_bridges":
        ix = int(rng.integers(1, cells_x - 4))
        iy = _safe_iy(rng, cfg)   # tight: only front-half iy
        return upright_bridges(ix, iy, cfg=cfg)

    if choice == "tower_on_bridge":
        ix = int(rng.integers(1, cells_x - 4))
        iy = _safe_iy(rng, cfg)
        tower_h = int(rng.integers(1, 3))   # 1 or 2 cubes on top
        return tower_on_bridge(ix, iy, cfg=cfg, tower_h=tower_h)

    if choice == "multi_tower":
        n = int(rng.integers(2, 5))   # 2..4 towers
        return multi_tower(rng, cfg=cfg, n_towers=n,
                                height_range=(2, 4))

    if choice == "staircase":
        n = int(rng.integers(3, 5))   # 3 or 4 steps
        ix = int(rng.integers(0, max(1, cells_x - 3 * n)))
        iy = _safe_iy(rng, cfg, max_iy_cap=cells_y - 2)
        return staircase(ix, iy, cfg=cfg, n=n)

    if choice == "double_bridges":
        if cells_x < 8:
            # Not enough room → fall back to single bridge.
            ix = int(rng.integers(1, cells_x - 4))
            iy = _safe_iy(rng, cfg)
            return upright_bridges(ix, iy, cfg=cfg)
        # Bias ix strongly toward 0 — the second bridge sits at ix+4,
        # so ix=0 puts both bridges in the proven-feasible left-half
        # ix∈[0,4].  Higher ix puts the second bridge at the ix=6+
        # boundary where the fast executor's cached IK posture clips.
        # Let some right-half samples slip through (10%) so the dataset
        # still has variety; rejected ones get retried.
        r = float(rng.random())
        if r < 0.70:
            ix = 0
        elif r < 0.90:
            ix = 1
        else:
            ix = int(rng.integers(2, cells_x - 7))
        iy = _safe_iy(rng, cfg)
        return double_bridges(ix, iy, cfg=cfg)

    if choice == "compound":
        return compound(rng, cfg=cfg,
                              n_substructures=int(rng.integers(2, 4)))

    if choice == "random_mix":
        return random_mix(rng, cfg=cfg)
    raise ValueError(f"unknown template: {choice}")


def _count_blocks_needed(template: Template) -> Dict[str, int]:
    """Return ``{shape: count}`` needed by template."""
    out: Dict[str, int] = {"cube": 0, "oblong": 0, "long": 0}
    for block, _, _ in template.source_placements:
        out[_block_shape(block)] += 1
    return out


def _make_cfg_for_template(template: Template, *,
                                base: Optional[MultilevelBlocksConfig] = None
                                ) -> MultilevelBlocksConfig:
    """Build a config with enough blocks for the template."""
    needs = _count_blocks_needed(template)
    if base is None:
        base = MultilevelBlocksConfig()
    kwargs = asdict(base)
    kwargs["n_cubes"] = max(kwargs.get("n_cubes", 0), needs["cube"])
    kwargs["n_oblong"] = max(kwargs.get("n_oblong", 0), needs["oblong"])
    kwargs["n_long"] = max(kwargs.get("n_long", 0), needs["long"])
    return MultilevelBlocksConfig(**kwargs)


def _generate_one(
    config_num: int,
    rng: np.random.Generator,
    args,
    env,
    workspace,
    cfg: MultilevelBlocksConfig,
    executor,
    output_dir: Path,
    split: str,
    render_now: bool = True,
    level: Optional[int] = None,
    level_subdir: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    """Generate a single instance.

    If ``level`` is provided, the sampler picks only templates from
    ``_LEVELS[level]`` and tags the plan metadata with the level.  If
    ``level_subdir`` is set, output goes to ``<output_dir>/<split>/<sub>``
    instead of ``<output_dir>/<split>``.
    """
    if level is not None:
        allowed = tuple(_LEVELS[level])
    else:
        allowed = tuple(args.templates)
    template = _sample_template(rng, cfg, allowed, level=level)

    # Build the plan from the template.
    plan = build_plan(template)

    # Validate.  L4 (put_upright templates) uses the FULL executor —
    # the FAST variant has unresolved IK basin bugs in put_upright's
    # lift-back stage.  Other levels use FAST (~10x faster).
    init_state = _state_from_placements(template.source_placements)
    use_fast = level not in _FULL_EXECUTOR_LEVELS
    seq_res = check_action_sequence(
        env, workspace, cfg, init_state, plan,
        fast=use_fast, short_circuit=True, executor=executor,
        # Per-action restore: judge each action on a freshly-restored
        # scene reflecting the symbolic state, matching training-time
        # ``check_action`` semantics.  Avoids the cumulative drift
        # where sequential ``dispatch_action`` calls leave blocks
        # ~30 mm off rest, eventually triggering spurious collision
        # rejections on downstream upright placements (compound /
        # double_bridges L5 templates).
        per_action_restore=True,
    )
    if not seq_res["success"]:
        return None

    # Write outputs.  level_subdir nests under split (e.g., val/L0/).
    if level_subdir is not None:
        problem_dir = output_dir / split / level_subdir
    else:
        problem_dir = output_dir / split
    viz_dir = problem_dir / "viz"
    problem_dir.mkdir(parents=True, exist_ok=True)
    if not args.no_viz:
        viz_dir.mkdir(parents=True, exist_ok=True)

    problem_path = problem_dir / f"config_{config_num}.pddl"
    plan_path = problem_dir / f"config_{config_num}.pddl.plan"
    viz_path = viz_dir / f"config_{config_num}.png"

    pn_sub = level_subdir + "-" if level_subdir else ""
    write_pddl_problem(
        template, workspace, cfg, problem_path,
        problem_name=f"multilevel-{split}-{pn_sub}{config_num}",
    )
    difficulty = template.metadata.get("difficulty", level)
    write_plan_file(plan, plan_path, metadata={
        "template": template.name,
        "difficulty": difficulty,
        "split": split,
        "config_num": config_num,
        "elapsed_s": f"{seq_res['elapsed_s']:.2f}",
    })
    if render_now and not args.no_viz:
        render_template_pair(template, workspace, cfg, env, viz_path)

    return {
        "template": template.name,
        "difficulty": difficulty,
        "plan_len": len(plan),
        "elapsed_s": seq_res["elapsed_s"],
        "config_num": config_num,
        "split": split,
        "template_obj": template,
        "viz_path": str(viz_path),
    }


def _init_stats() -> dict:
    return {
        "attempts": 0, "accepted": 0,
        "reject_plan_failed": 0,
        "templates": Counter(),
        "plan_len_hist": Counter(),
        "gen_seconds": [],
    }


def _generate_split(
    split: str,
    count: int,
    args,
    output_base: Path,
    seed: int,
    *,
    level: Optional[int] = None,
    level_subdir: Optional[str] = None,
    config_offset: int = 0,
) -> dict:
    """Single-process split runner."""
    if count <= 0:
        return _init_stats()
    rng = np.random.default_rng(seed)

    cfg = MultilevelBlocksConfig(n_cubes=20, n_oblong=12, n_long=6)
    use_full = level in _FULL_EXECUTOR_LEVELS
    with tempfile.TemporaryDirectory(prefix="mlb_data_") as td:
        builder, ws, cfg = make_multilevel_blocks_builder(
            scratch_dir=Path(td), config=cfg)
        env = builder.build_env(rate=10000.0)
        _maybe_disable_hand_capsule(env, args)
        executor = _make_executor(env, ws, cfg, fast=not use_full)

        stats = _init_stats()
        t_start = time.time()
        config_num = config_offset
        # 60× retry budget per accepted problem.  Was 30; bumped so L5
        # upright templates (compound w/ right-half upright sub or
        # double_bridges with high ix), which reject ~91 % of the time
        # due to LUT-cached-posture clipping at boundary stack cells,
        # still get enough samples through to fill the per-level quota.
        max_attempts = count * 60
        while stats["accepted"] < count and stats["attempts"] < max_attempts:
            stats["attempts"] += 1
            config_num += 1
            try:
                res = _generate_one(
                    config_num, rng, args, env, ws, cfg,
                    executor, output_base, split,
                    level=level, level_subdir=level_subdir,
                )
            except Exception as exc:
                stats["reject_plan_failed"] += 1
                if args.verbose:
                    print(f"  [{split}] attempt {stats['attempts']} "
                              f"raised {type(exc).__name__}: {exc}")
                continue
            if res is None:
                stats["reject_plan_failed"] += 1
                continue

            stats["accepted"] += 1
            stats["templates"][res["template"]] += 1
            stats["plan_len_hist"][res["plan_len"]] += 1
            stats["gen_seconds"].append(res["elapsed_s"])

            if stats["accepted"] % 10 == 0 or stats["accepted"] == 1:
                elapsed = time.time() - t_start
                eta = elapsed / stats["accepted"] * (count - stats["accepted"])
                print(f"  [{split}] {stats['accepted']}/{count}  "
                          f"plan_len={res['plan_len']}  "
                          f"elapsed={elapsed:.0f}s  eta={eta:.0f}s  "
                          f"accept={stats['accepted']}/"
                          f"{stats['attempts']}")
    return stats


# ---------------------------------------------------------------------------
# Parallel worker
# ---------------------------------------------------------------------------


def _worker(worker_id: int, split: str, start_idx: int, count: int,
                 args, output_base_str: str, seed: int,
                 level: Optional[int] = None,
                 level_subdir: Optional[str] = None) -> Tuple[dict, list]:
    """One worker process: generates `count` instances into the split.

    ``level`` (0..5) filters the template sampler; ``level_subdir``
    nests output under ``<output_dir>/<split>/<subdir>``.  Both are
    None for the legacy mixed-train flow.
    """
    rng = np.random.default_rng(seed + worker_id * 9999)
    output_base = Path(output_base_str)
    cfg = MultilevelBlocksConfig(n_cubes=20, n_oblong=12, n_long=6)
    render_tasks: list = []
    use_full = level in _FULL_EXECUTOR_LEVELS
    with tempfile.TemporaryDirectory(prefix="mlb_data_") as td:
        builder, ws, cfg = make_multilevel_blocks_builder(
            scratch_dir=Path(td), config=cfg)
        env = builder.build_env(rate=10000.0)
        _maybe_disable_hand_capsule(env, args)
        executor = _make_executor(env, ws, cfg, fast=not use_full)

        stats = _init_stats()
        config_num = start_idx
        # 60× retry budget per accepted problem.  Was 30; bumped so L5
        # upright templates (compound w/ right-half upright sub or
        # double_bridges with high ix), which reject ~91 % of the time
        # due to LUT-cached-posture clipping at boundary stack cells,
        # still get enough samples through to fill the per-level quota.
        max_attempts = count * 60  # safety cap so an impossible level
                                          # can't loop forever
        while stats["accepted"] < count and stats["attempts"] < max_attempts:
            stats["attempts"] += 1
            try:
                res = _generate_one(
                    config_num, rng, args, env, ws, cfg, executor,
                    output_base, split, render_now=False,
                    level=level, level_subdir=level_subdir,
                )
            except Exception:
                stats["reject_plan_failed"] += 1
                continue
            if res is None:
                stats["reject_plan_failed"] += 1
                continue
            stats["accepted"] += 1
            stats["templates"][res["template"]] += 1
            stats["plan_len_hist"][res["plan_len"]] += 1
            stats["gen_seconds"].append(res["elapsed_s"])
            if not args.no_viz:
                render_tasks.append(
                    (res["config_num"], res["viz_path"],
                          res["template_obj"]))
            config_num += 1
    return stats, render_tasks


def _generate_split_parallel(
    split: str, count: int, args,
    output_base: Path, seed: int,
    *,
    level: Optional[int] = None,
    level_subdir: Optional[str] = None,
    config_offset: int = 0,
) -> dict:
    """Multi-worker split runner.

    Optional ``level`` filters templates; ``level_subdir`` nests output
    under ``<split>/<subdir>``.  ``config_offset`` shifts the starting
    config_num so multiple level chunks under the same split don't
    collide on filenames (used when generating mixed-train across
    levels in sequence).
    """
    if count <= 0:
        return _init_stats()
    n_workers = args.num_workers
    per_worker = count // n_workers
    remainder = count - per_worker * n_workers
    chunks = []
    cursor = 1 + config_offset
    for w in range(n_workers):
        c = per_worker + (1 if w < remainder else 0)
        chunks.append((w, split, cursor, c, args, str(output_base), seed,
                            level, level_subdir))
        cursor += c

    ctx = mp.get_context("fork")
    with ctx.Pool(n_workers) as pool:
        results = pool.starmap(_worker, chunks)

    # Merge stats and collect render tasks.
    merged = _init_stats()
    all_render: list = []
    for s, render_tasks in results:
        merged["attempts"] += s["attempts"]
        merged["accepted"] += s["accepted"]
        merged["reject_plan_failed"] += s["reject_plan_failed"]
        merged["templates"].update(s["templates"])
        merged["plan_len_hist"].update(s["plan_len_hist"])
        merged["gen_seconds"].extend(s["gen_seconds"])
        all_render.extend(render_tasks)

    # Serial viz pass in main process.
    if all_render:
        all_render.sort(key=lambda t: t[0])   # by config_num
        print(f"  [{split}] rendering {len(all_render)} viz "
                  f"(serial, post-pool)...")
        cfg = MultilevelBlocksConfig(n_cubes=20, n_oblong=12, n_long=6)
        with tempfile.TemporaryDirectory(prefix="mlb_viz_") as td:
            builder, ws, cfg = make_multilevel_blocks_builder(
                scratch_dir=Path(td), config=cfg)
            env = builder.build_env(rate=10000.0)
            _maybe_disable_hand_capsule(env, args)
            t_viz = time.time()
            for config_num, viz_path, template in all_render:
                try:
                    render_template_pair(template, ws, cfg, env,
                                                Path(viz_path))
                except Exception as exc:
                    print(f"    viz {config_num} failed: "
                              f"{type(exc).__name__}: {exc}")
            print(f"  [{split}] viz done in {time.time() - t_viz:.1f}s")

    return merged


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _print_stats(split: str, stats: dict, elapsed: float) -> None:
    print(f"\n=== {split} summary ===")
    print(f"  accepted/attempts: {stats['accepted']}/{stats['attempts']}")
    if stats['attempts']:
        print(f"  reject rate: {100*stats['reject_plan_failed']/stats['attempts']:.1f}%")
    print(f"  elapsed: {elapsed:.1f}s")
    if stats["gen_seconds"]:
        mean = sum(stats["gen_seconds"]) / len(stats["gen_seconds"])
        print(f"  mean gen time: {mean:.2f}s")
    print(f"  templates: {dict(stats['templates'])}")
    print(f"  plan length distribution: {dict(stats['plan_len_hist'])}")


def _run_curriculum(split: str, spec: List[Tuple[int, int]], args,
                         output_base: Path, base_seed: int,
                         *, per_level_subdirs: bool) -> Dict[int, dict]:
    """Generate a split following a curriculum spec.

    ``spec``: list of ``(level, count)`` tuples (one entry per level).
    ``per_level_subdirs``: True → each level into ``<split>/L{k}/``;
                              False → all levels into flat ``<split>/``.
    Returns ``{level: stats_dict}``.
    """
    out: Dict[int, dict] = {}
    config_offset = getattr(args, "config_offset", 0) or 0
    for level, count in spec:
        if count <= 0:
            continue
        subdir = f"L{level}" if per_level_subdirs else None
        seed = base_seed + level * 7919
        t = time.time()
        # In flat-train mode, restart numbering per level so all configs
        # exist in train/ without collision via the offset.
        if not per_level_subdirs:
            offset = config_offset
        else:
            offset = 0
        if args.num_workers > 1:
            stats = _generate_split_parallel(
                split, count, args, output_base, seed,
                level=level, level_subdir=subdir,
                config_offset=offset,
            )
        else:
            stats = _generate_split(
                split, count, args, output_base, seed,
                level=level, level_subdir=subdir,
                config_offset=offset,
            )
        _print_stats(f"{split}/L{level}", stats, time.time() - t)
        out[level] = stats
        if not per_level_subdirs:
            config_offset += stats["accepted"]
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=_DEFAULT_OUTPUT_DIR)
    parser.add_argument("--num-train", type=int, default=_DEFAULT_TRAIN)
    parser.add_argument("--num-test", type=int, default=_DEFAULT_TEST)
    parser.add_argument("--num-val", type=int, default=_DEFAULT_VAL)
    parser.add_argument("--templates", nargs="+",
                            default=list(_TEMPLATE_NAMES),
                            choices=_TEMPLATE_NAMES)
    parser.add_argument(
        "--curriculum-spec", type=str, default=None,
        choices=sorted(_CURRICULA.keys()),
        help=("If set, override --num-train/--templates with a curated "
                  "level-mix preset.  Use train_200/train_400/train_600 for "
                  "the train split (flat output), val_per_level / "
                  "test_per_level for validation/test (per-level subdirs)."),
    )
    parser.add_argument(
        "--curriculum-split", type=str, default="train",
        choices=("train", "val", "test", "train_l0_l4"),
        help=("Which split the --curriculum-spec writes to.  ``train`` and "
                  "``train_l0_l4`` use a flat output directory; val/test use "
                  "per-level subdirs.  ``train_l0_l4`` pairs with the curriculum "
                  "spec of the same name (no L5) — used so the OOD train "
                  "dataset lands at <output_dir>/train_l0_l4/ without "
                  "overwriting the in-distribution <output_dir>/train/."),
    )
    parser.add_argument(
        "--level", type=int, default=None, choices=list(range(6)),
        help=("Override curriculum-spec to generate only this level.  "
                  "Used by the per-level shell driver to sidestep the "
                  "fork-pool reuse deadlock observed when one Python "
                  "process drives multiple sequential pools."),
    )
    parser.add_argument(
        "--config-offset", type=int, default=0,
        help=("Shift the starting config_num for filename numbering.  "
                  "Used together with --level so a multi-level dataset "
                  "split across subprocess invocations doesn't collide "
                  "on filenames in a flat output dir."),
    )
    parser.add_argument("--num-workers", type=int, default=_DEFAULT_NUM_WORKERS)
    parser.add_argument("--seed", type=int, default=_DEFAULT_SEED)
    parser.add_argument("--no-viz", action="store_true")
    parser.add_argument(
        "--enable-hand-capsule", action="store_true",
        help=("Leave the Franka hand_capsule bounding-capsule active.  "
                  "Default is DISABLED — the 4cm/6cm capsule's 10cm axial "
                  "extent over-rejects feasible put_upright plans (L4 "
                  "templates fail 100%% with it on).  Disabling falls back "
                  "to the hand_c mesh, which still detects real "
                  "collisions."),
    )
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    output_base = args.output_dir.resolve()
    output_base.mkdir(parents=True, exist_ok=True)
    shutil.copy(_DOMAIN_BUNDLED, output_base / "domain.pddl")
    print(f"Output base: {output_base}")
    print(f"Templates: {args.templates}")
    print(f"Workers: {args.num_workers}")

    if args.curriculum_spec is not None:
        spec = _CURRICULA[args.curriculum_spec]
        split = args.curriculum_split
        per_level_subdirs = (split in ("val", "test"))
        # If --level filter is given, run only that level (so a shell
        # driver can dispatch one Python process per level — avoids the
        # fork-pool reuse hang).
        if args.level is not None:
            spec = [(lvl, cnt) for lvl, cnt in spec if lvl == args.level]
        print(f"\nCurriculum preset: {args.curriculum_spec!r}  "
                  f"split={split}  per_level_subdirs={per_level_subdirs}  "
                  f"level_filter={args.level}")
        _run_curriculum(split, spec, args, output_base,
                              args.seed + hash(args.curriculum_spec) % 9999,
                              per_level_subdirs=per_level_subdirs)
        return 0

    splits = [
        ("train", args.num_train),
        ("test", args.num_test),
        ("val", args.num_val),
    ]
    for split, count in splits:
        if count <= 0:
            continue
        t = time.time()
        if args.num_workers > 1:
            stats = _generate_split_parallel(split, count, args, output_base,
                                                      args.seed + hash(split) % 9999)
        else:
            stats = _generate_split(split, count, args, output_base,
                                             args.seed + hash(split) % 9999)
        _print_stats(split, stats, time.time() - t)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
